export const config = {
  'zh': {
    'course': {
      'pre_class': '课前',
      'in_class': '已上课',
      'end_class': '课程已结束',
    },
    'scaffold': {
      'pencil': '画笔',
      'laser_pointer': '激光笔',
      'straight': '直线',
      'circle': '圆圈',
      'rectangle': '矩形',
      'selector': '选择',
      'eraser': '橡皮擦',
      'color': '颜色',
      'blank_page': '新增一页',
      'move': '移动工具',
      'follow': '跟随模式',
      'un_follow': '解除跟随',
      'screen_share': '屏幕共享',
      'stop_screen_share': '停止共享',
      'cloud_storage': '云盘',
      'text': '文本',
      'tools': '工具栏'
    },
    'cloud': {
      'fileName': '文件名字',
      'size': '大小',
      'progress': '进度条',
      'updatedAt': '修改时间',
      'publicResources': '公共资源',
      'personalResources': '我的资源',
      'downloadResources': '下载资源',
      'upload': '上传',
      'delete': '删除',
      'download': '下载',
      'downloading': '下载中',
      'pause': '暂停'
    },
    'media': {
      'camera': '摄像头',
      'switch_camera': '切换摄像头',
      'microphone': '麦克风',
      'switch_microphone': '切换麦克风',
      'microphone_volume': '麦克风音量',
      'speaker': '扬声器',
      'switch_speaker': '切换扬声器',
      'volume': '音量',
      'adjust_volume': '调整音量',
      'test_speaker': '扬声器检测',
      'camera_error': '摄像头被拔出或摄像头已占用，无法显示视频！',
      'microphone_error': '麦克风被拔出或麦克风被占用，无法使用麦克风！',
      'mirror': '镜像模式',
    },
    'pretest': {
      'title': '设备检测',
      'finishTest': '完成'
    },
    'message': '消息',
    'zh': '中文',
    'nav': {
      'delay': '延迟: ',
      'network': '网络: ',
      'cpu': 'CPU: ',
      'class_end': '课程结束',
      'class_start': '课程开始',
      'back': '返回',
      'to_start_in': '距离上课还有：',
      'started_elapse': '已开始上课：',
      'hours': '小时',
      'minutes': '分',
      'seconds': '秒',
      'short': {
        'hours': '小时',
        'minutes': '分钟',
        'seconds': '秒',
      },
      'signal_good': '优',
      'signal_weak': '良',
      'signal_bad': '差',
      'signal_unknown': '未知',
    },
  },
  'en': {
    'course': {
      'pre_class': 'Pre Class',
      'in_class': 'In Class',
      'end_class': 'End Class',
    },
    'scaffold': {
      'pencil': 'Pencil',
      'laser_pointer': 'Laser pointer',
      'straight': 'straight',
      'circle': 'circle',
      'rectangle': 'rectangle',
      'selector': 'selector',
      'eraser': 'eraser',
      'color': 'color',
      'blank_page': 'add page',
      'move': 'move',
      'follow': 'Follow',
      'un_follow': 'UnFollow',
      'screen_share': 'Screen Share',
      'stop_screen_share': 'Stop Screen Share',
      'cloud_storage': 'Cloud Storage',
      'text': 'Text',
      'tools': 'Tools'
    },
    'message': 'message',
    'en': 'English',
    'cloud': {
      'fileName': 'file name',
      'size': 'size',
      'progress': 'progress',
      'updatedAt': 'updated at',
      'publicResources': 'Public Resources',
      'personalResources': 'Personal Resources',
      'downloadResources': 'Download Resources',
      'upload': 'Upload',
      'delete': 'Delete',
      'download': 'Download',
      'downloading': 'Downloading',
      'pause': 'Pause',
    },
    'media': {
      'camera': 'Camera',
      'switch_camera': 'Switch Camera',
      'microphone': 'Microphone',
      'switch_microphone': 'Switch Microphone',
      'microphone_volume': 'Microphone Volume',
      'speaker': 'Speaker',
      'switch_speaker': 'Switch Speaker',
      'volume': 'Volume',
      'adjust_volume': 'Adjust Volume',
      'test_speaker': 'Test Playback',
      'camera_error': 'Device exception, camera is unplugged or occupied and cannot be used!',
      'microphone_error': 'Device exception, microphone is unplugged or occupied and cannot be used!',
      'mirror': 'mirror',
    },
    'pretest': {
      'title': 'Device Test',
      'finishTest': 'Finish'
    },
    'nav': {
      'delay': 'Delay: ',
      'network': 'Network: ',
      'cpu': 'CPU: ',
      'class_end': 'Class end',
      'class_start': 'Class start',
      'back': 'Back',
      'to_start_in': 'To start in: ',
      'started_elapse': 'Started: ',
      'hours': 'hours',
      'minutes': 'minutes',
      'seconds': 'seconds',
      'short': {
        'hours': 'hrs',
        'minutes': 'mins',
        'seconds': 'secs',
      },
      'signal_good': 'Good',
      'signal_weak': 'Weak',
      'signal_bad': 'Bad',
      'signal_unknown': 'Unknown',
    },
  }
}