export const en = {
  'Close Microphone': 'Close microphone',
  'Open Microphone': 'Open microphone',
  'Camera Not Available': 'Camera Not Available',
  'Microphone Not Available': 'Microphone Not Available',
  'Close Camera': 'Close camera',
  'Open Camera': 'Open camera',
  'Clear Podium': 'Down stage',
  'Clear Podiums': 'Clear the stage',
  'Close Whiteboard': 'Cancel Authorize',
  'Whiteboard Not Available': 'Whiteboard Not Available',
  'Open Whiteboard': 'Authorize',
  Star: 'Reward',
  'Open Private Call': 'Open private call',
  'Close Private Call': 'Close private call',
  'Camera Pos Reset': 'Reset camera',
  role: {
    teacher: 'Teacher',
    student: 'Student',
    assistant: 'Assistant',
  },
  chat: {
    send_to_all: 'Broadcast Message',
  },
  disabled: 'Disabled',
  whiteboard: {
    'upload-success': 'Upload Success',
    'upload-error': 'Upload Error',
    converting: 'Converting',
    'disconnect-img-alt': 'Whiteboard Disconnected',
    'disconnect-btn': 'Connect Again',
    'courseWare-loading': 'Courseware Loading...',
    'h5-courseWare': 'HTML5 Courseware',
    'test-courseWare': 'Test Courseware',
    loading: 'Please wait...',
  },
  screen_share: 'Screen Share',
  kick: {
    kick_out_student: 'Remove students',
  },
  radio: {
    kicked_once: 'Remove the student from the classroom',
    ban: 'Ban the student from re-entering the classroom',
  },
  course: {
    pre_class: 'Pre Class',
    in_class: 'In Class',
    end_class: 'End Class',
    join_failed: 'Join Failure',
    screen_sharing: 'Screen Sharing',
  },
  device: {
    camera: 'Camera',
    speaker: 'Speaker',
    microphone: 'Microphone',
    microphone_volume: 'Microphone Volume',
    speaker_volume: 'Speaker Volume',
    stage_area: 'Podium',
  },
  roster: {
    chat: 'Mute Chat',
    teacher_name: 'Teacher:',
    user_list: 'Roster',
    student_name: 'Student',
    student_co_video: 'Stage',
    camera_state: 'Camera',
    microphone_state: 'Microphone',
    reward: 'Reward',
    kick: 'Remove',
    granted: 'Auth',
    shift: 'Video carousel',
    everyone: 'Everyone',
    available: 'Available',
    students_in: 'students in',
    sequence: 'sequence',
    random: 'random',
    order_every: 'order every',
    seconds: 'seconds',
    no_more_data: 'No more data',
    supervise_student: 'Supervise',
  },
  hands_up: 'Hands Up',
  on_podium_max_count:
    'The number of people on stage has reached the upper limit, and students cannot be invited to stage',
  hands_up_tip: 'Press and hold down',
  co_video: {
    remote_open_camera: 'Your camera has been turned on',
    remote_open_microphone: 'Your mic has been turned on',
    remote_grant_board: 'You can now use the whiteboard tools',
    remote_close_camera: 'Your camera has been turned off',
    remote_close_microphone: 'Your mic has been turned off',
    remote_revoke_board: 'You cannot use the whiteboard tools',
    received_student_hands_up: 'A student wants to get on the stage',
    received_teacher_accepted: 'Teacher Accepted',
    received_teacher_refused: 'Teacher Refused',
    received_student_cancel: 'Teacher Cancelled',
    received_message_timeout: 'No Response. Try again?',
    hands_up_requsted: 'Your request has been sent',
    hands_up_cancelled: 'Your request has been cancelled',
  },
  private_media_chat: {
    chat_started: 'Private media chat started',
    chat_ended: 'Private media chat ended',
  },
  signal: {
    delay: 'Delay',
    lose: 'Packet Loss',
    status: 'Status',
    CPU: 'CPU',
    receive: 'Receive',
    send: 'Send',
  },
  placeholder: {
    muted_chat: 'Muted Chat',
    empty_chat: 'Empty Message',
    empty_quiz: 'Empty Question',
    enable_chat_muted: 'Student Chat Muted',
    input_message: 'Please Input Message',
  },
  error: {
    banned: 'Prohibited',
    cannot_join: 'You are prohibited from entering classroom.',
    conflict: 'Hands Up Conflict',
    not_found: 'Page Not Found',
    apply_co_video_limit: 'Onstage student limit is reached.',
    send_co_video_limit: 'Roll call co-video over maximum',
    components: {
      paramsEmpty: 'params：{reason} can`t be empty',
    },
    class_end: 'The class has ended.',
    unknown: 'Unknown error occured. Code: {errCode} Details: {message}',
    room_is_full: 'The room is full',
    network_timeout: 'Network request timeout',
  },
  toast: {
    mute_chat: 'You were silenced by {hostName}',
    unmute_chat: 'You were allowed to chat by {hostName}',
    remote_mute_chat: '{studentName} was silenced by {hostName}',
    remote_unmute_chat: '{studentName} was allowed to chat by {hostName}',
    add_screen_share: 'Teacher starts to the screen share',
    remove_screen_share: 'Teacher stops the screen share',
    granted_board_success: 'Grant Permission success',
    revoke_board_success: 'Revoke Permission success',
    create_screen_share_failed: 'Create screen share failed',
    kick_by_other_side: 'Kick out by other client',
    screen_share: {
      title: 'Screen Share',
    },
    close_ppt: 'Close CourseWare',
    sure_close_ppt: 'Are you sure to close?',
    end_class: 'End Class',
    quit_from_room: 'Leave Class Room',
    kick_by_teacher: 'You have been removed from the classroom',
    upload_log_failure: 'Upload Log Failure，ErrorName:{reason}，see more details in devtool.',
    show_log_id: `Report your log ID: {reason}`,
    api_login_failured: 'Join Failured, Reason: {reason}',
    confirm: 'Confirm',
    cancel: 'Cancel',
    leave_room: 'Leave Classroom',
    quit_room: 'You want to exit the classroom?',
    login_failure: 'login failure',
    whiteboard_lock: 'Whiteboard follow',
    whiteboard_unlock: 'Whiteboard nofollow',
    canceled_screen_share: 'Canceled screen sharing',
    screen_sharing_failed: 'Screen sharing failed, reason: {reason}',
    recording_failed: 'Start cloud recording failed, reason: {reason}',
    start_recording: {
      title: 'Start Recording',
      body: 'Are you sure to start recording the classroom?',
      success: 'Recording successfully started',
    },
    stop_recording: {
      title: 'Recording stopped',
      body: 'Stop recording the classroom?',
      success: 'Recording successfully stopped.',
    },
    recording_too_short: 'Recording must be at least 15 seconds',
    rtm_login_failed: 'login failure, please check your network',
    rtm_login_failed_reason: 'login failure, reason: {reason}',
    replay_failed: 'Replay failed please refresh browser',
    teacher_exists: 'Teacher existed. Please wait 30s or reopen a new class.',
    student_over_limit:
      'Number of Students exceeds maximum. Please waiting 30s or join a new class',
    teacher_and_student_over_limit:
      'The number of students and teacher have reached the upper limit',
    teacher_accept_whiteboard: 'Teacher already granted your whiteboard',
    teacher_cancel_whiteboard: 'Teacher already cancel your whiteboard',
    teacher_accept_co_video: 'Teacher already accept co-video',
    teacher_reject_co_video: 'Teacher already rejected co-video',
    teacher_cancel_co_video: 'Teacher already cancelled co-video',
    student_cancel_co_video: 'Student cancelled co-video',
    student_peer_leave: '"{reason}" Left',
    student_send_co_video_apply: '"{reason}" send the co-video request',
    stop_co_video: 'Stop "{reason}" co-video',
    reject_co_video: 'Reject co-video',
    close_co_video: 'Close co-video',
    close_youself_co_video: 'Stop co-video',
    accept_co_video: 'Accept co-video',
    successfully_joined_the_room: 'Successfully joined the room',
    failed_to_join_the_room: 'Failed to join the room',
    failed_to_authorize_whiteboard: 'Failed to authorize whiteboard',
    failed_to_deauthorize_whiteboard: 'Failed to deauthorize whiteboard',
    failed_to_query_playback_list: 'Failed to query playback list',
    audio_equipment_has_changed: 'Audio equipment has changed',
    video_equipment_has_changed: 'Video equipment has changed',
    failed_to_initiate_screen_sharing: 'Failed to initiate screen sharing',
    failed_to_end_screen_sharing: 'Failed to end screen sharing',
    failed_to_initiate_screen_sharing_to_remote: 'Failed to initiate screen sharing to remote',
    failed_to_enable_screen_sharing: 'Failed to enable screen sharing',
    failed_to_enable_screen_sharing_permission_denied:
      'Open screen capture failed. Please grant permission for screen capture.',
    failed_to_send_chat: 'Failed to send chat',
    failed_to_translate_chat: 'Failed to translate chat',
    failed_to_send_reward: 'Failed to send reward',
    failed_to_join_rtc_please_refresh_and_try_again:
      'Failed to join RTC, please refresh and try again',
    leave_rtc_channel: 'Leave RTC channel',
    failed_to_leave_rtc: 'Failed to leave RTC',
    co_video_close_success: 'On Stage dismissed success',
    co_video_close_failed: 'On Stage dismissed failure',
    publish_rtc_success: 'Publish RTC Success',
    open_whiteboard_follow: 'open whiteboard follow',
    close_whiteboard_follow: 'close whiteboard follow',
    i: 'I',
    teacher: 'Teacher',
    the_teacher_authorized_your_whiteboard: 'The teacher invites you to the whiteboard',
    the_teacher_cancelled_your_whiteboard_permission:
      'The teacher cancelled your whiteboard permission',
    publish_business_flow_successfully: 'Publish business flow successfully',
    media_method_call_failed: 'Media method call failed',
    successfully_left_the_business_channel: 'Successfully left the business channel',
    course_started_successfully: 'Course start successfully',
    setting_start_failed: 'Setting start failed',
    the_course_ends_successfully: 'Course end successfully',
    setting_ended_failed: 'Setting ended failed',
    start_recording_successfully: 'Start recording successfully',
    start_recording_failed: 'Start recording failed',
    successfully_ended_recording: 'Successfully_ended_recording',
    failed_to_end_recording: 'Failed to end recording',
    you_have_a_default_message: 'You have a default message',
    the_teacher_agreed: 'Teacher Agreed',
    student_applied: 'Student applied',
    you_were_dismissed_by_the_teacher: 'You were dismissed by the teacher',
    student_canceled: 'Student cancelled',
    the_teacher_refused: 'Teacher refused',
    failed_to_initiate_a_raise_of_hand_application:
      'Failed to initiate a raise of hand application',
    failed_to_end_the_call: 'Failed to end the call',
    failed_to_join_board: 'Failed to join board',
    stop_screen_share_failed: 'Stop screen share failed',
    classroom_remote_join: 'Account was logged in from remote device, you have left the classroom',
    time_interval_between_start: `The class will start in {reason} minutes`,
    time_interval_between_end: `The class will be over in {reason} minutes`,
    class_is_end: `Class is over. The classroom will be closed in {reason} minutes`,
    time_interval_between_close: `The classroom will be closed in {reason} minutes`,
    reward_limit: 'The maximum number of trophies in this class has been reached',
    chat_enable: 'Enable Mute Chat',
    chat_disable: 'Disable Mute Chat',
    upload_failure: 'Upload Failure',
    download_success: 'Download Success',
    download_failure: 'Download Failure',
    resource_already_opened: 'This resource is already opened',
    resource_is_converting: 'The resource is converting',
    fail_to_convert_resource: 'The resource conversion failed',
    interaction_too_frequent: 'The operation is too frequent, please try again later.',
    breakout_room_group_name_existed: 'The group name already exists',
    start_group: 'Please create a group first',
    close_whiteboard: 'Close Whitboard',
    close_whiteboard_confirm: 'Are you sure you want to close the whiteboard?',
    clear_whiteboard: 'Clear Content',
    clear_whiteboard_confirm: 'Are you sure you want to clear all content？',
  },
  end_class_confirm: 'Confirm the end of class?',
  notice: {
    student_interactive_apply: `"{reason}" want to co-video`,
  },
  scaffold: {
    clear: 'Clear',
    undo: 'Undo',
    redo: 'Redo',
    search: 'Search',
    pencil: 'Pencil',
    laser_pointer: 'Laser pointer',
    whiteboard: 'Whiteboard',
    straight: 'Straight',
    circle: 'Circle',
    rectangle: 'Rectangle',
    arrow: 'Arrow',
    pentagram: 'Pentagram',
    rhombus: 'Rhombus',
    triangle: 'Triangle',
    selector: 'Selector',
    clicker: 'Mouse',
    eraser: 'Eraser',
    color: 'Color',
    blank_page: 'Add page',
    move: 'Move',
    follow: 'Follow',
    un_follow: 'Unfollow',
    screen_share: 'Screen Share',
    stop_screen_share: 'Stop Screen Share',
    cloud_storage: 'Cloud Storage',
    text: 'Text',
    tools: 'Tools',
    user_list: 'User List',
    breakout_room: 'Breakout Room',
    in_progress: '-In progress',
    not_in_progress: '-Not started',
    register: 'Roster',
    save: 'Save the canvas',
    slice: 'Screenshot',
    slice_window: 'Hide the screenshot',
  },
  message: 'Message',
  quiz: 'Question',
  en: 'English',
  cloud: {
    fileName: 'File name',
    size: 'Size',
    progress: 'Progress',
    updated_at: 'Updated at',
    operation: 'Operation',
    publicResources: 'Public Resources',
    deleteTip: 'Delete the selected file?',
    personalResources: 'Personal Resources',
    downloadResources: 'Download Resources',
    upload: 'Upload',
    delete: 'Delete',
    download: 'Download',
    downloading: 'Download',
    pause: 'Pause',
    upload_success: 'Upload Success',
    supprotTypeTitle: 'Supported file formats',
    fileType: 'Type',
    ppt: 'PPT',
    word: 'Word',
    excel: 'Excel',
    pdf: 'Pdf',
    video: 'Video',
    audio: 'Audio',
    txt: 'Txt',
    photo: 'Photo',
    fileCounts: '{fileCounts} items',
  },
  media: {
    camera: 'Camera',
    switch_camera: 'Switch Camera',
    microphone: 'Microphone',
    switch_microphone: 'Switch Microphone',
    microphone_volume: 'Microphone Volume',
    speaker: 'Speaker',
    switch_speaker: 'Switch Speaker',
    volume: 'Volume',
    adjust_volume: 'Adjust Volume',
    test_speaker: 'Test Speaker',
    camera_error: 'Device exception, camera is unplugged or occupied and cannot be used.',
    microphone_error: 'Device exception, microphone is unplugged or occupied and cannot be used.',
    mirror: 'Mirror',
    beauty: 'Beauty',
    whitening: 'Whitening',
    buffing: 'Buffing',
    ruddy: 'Ruddy',
    default: 'Default',
  },
  stage: {
    visible: 'Show',
    hidden: 'Hide',
  },
  pretest: {
    title: 'Device Test',
    settingTitle: 'Device Setting',
    finishTest: 'Finish',
    detect_new_device: 'The device is now installed, Please try it!',
    camera_move_out: 'Camera is pulled out, unable to display video!',
    mic_move_out: 'Microphone is pulled out!',
    device_move_out: 'Device is pulled out!',
    playback_move_out: 'Speaker is pulled out!',
    device_not_working: 'The device is not working properly!',
    detect_new_device_in_room:
      'The device has installed, Please click setting and select the new device.',
    teacher_device_may_not_work: "There is something wrong with the teacher's device",
  },
  'biz-header': {
    perf: 'Perf',
    setting: 'Setting',
    exit: 'Exit',
    recording: 'Recording...',
    start_record: 'Start Recording',
    stop_record: 'Stop Recording',
    record_starting: 'Recording is preparing, please wait',
  },
  nav: {
    delay: 'Delay: ',
    network: 'Network: ',
    cpu: 'CPU: ',
    class_end: 'Class end',
    class_start: 'Class start',
    back: 'Back',
    to_start_in: 'To start in: ',
    started_elapse: 'Started: ',
    ended_elapse: 'Ended: ',
    class_not_started: 'Class has not started',
    hours: 'hours',
    minutes: 'minutes',
    seconds: 'seconds',
    ms: 'ms',
    short: {
      hours: 'hrs',
      minutes: 'mins',
      seconds: 'secs',
    },
    signal_excellent: 'Excellent',
    signal_good: 'Good',
    signal_weak: 'Weak',
    signal_bad: 'Bad',
    signal_unknown: 'Unknown',
    signal_down: 'down',
    singal_poor_tip: 'Poor local network connection, please check the network connection.',
    singal_down_tip: 'The local network is disconnected, please check the network connection.',
  },
  send: 'Send',
  home: {
    form_title: 'Free Use',
    roomId: 'RoomId',
    roomId_placeholder: 'Please input roomId',
    userId: 'UserId',
    userId_placeholder: 'Please input userId',
    roomName: 'Room',
    roomName_placeholder: 'Please input room name',
    nickName: 'Name',
    nickName_placeholder: 'Please input your name',
    roomType: 'Type',
    roomType_placeholder: 'Please select class type',
    serviceType: 'Service',
    serviceType_placeholder: 'Please select voice and video service',
    serviceType_premium: 'Interactive Live Streaming Premium',
    serviceType_standard: 'Interactive Live Streaming Standard',
    serviceType_latency: 'Standard Latency Streaming (CDN)',
    serviceType_mix: 'Mix Streaming（CDN&RTC）',
    serviceType_mix_stream_cdn: 'Mix Streaming CDN',
    serviceType_hosting_scene: 'Hosting Scene',
    roomType_1v1: 'One to One Classroom',
    roomType_interactiveSmallClass: 'Interactive Small Classroom',
    roomType_interactiveBigClass: 'Lecture Hall',
    roomType_vocationalClass: 'Vocational Lecture Hall',
    role: 'Role',
    role_placeholder: 'Please select your role',
    encryptionMode: 'Mode',
    encryptionMode_placeholder: 'Please select your mode',
    encryptionKey: 'Key',
    encryptionKey_placeholder: 'Please input your key',
    role_teacher: 'Teacher',
    role_student: 'Student',
    role_assistant: 'Assistant',
    role_audience: 'Audience',
    role_observer: 'Observer',
    language: 'Language:',
    language_placeholder: 'Please choose language',
    duration: 'Duration',
    duration_unit: 'mins',
    enter_classroom: 'Enter',
    region_placeholder: 'Please choose region',
    region: 'Region:',
    'header-left-title': 'Agora Flexible Classroom',
    about: 'About',
    'input-error-msg': 'Between 6 and 50 characters,letter or number only',
    'input-username-error-msg': 'Between 3 and 25 characters,letter or number only',
    network_error: 'Network error, please try again later',
    'recordation-search': 'Recordation',
    'recordation-tip': 'Recordations only within 1 hour',
    replay: 'replay',
    search: 'search',
    system_name: 'Agora Flexible Classroom',
  },
  'home-about': {
    'privacy-policy': 'Privacy Policy',
    'product-disclaimer': 'Product Disclaimer',
    'sign-up': 'Sign up Agora.io',
    'build-time': 'Build Time',
    'sdk-version': 'SDK Version',
    'classroom-version': 'Flexible Classroom Version',
    'commit-id': 'Commit ID',
    check: 'View',
    register: 'Sign up',
  },
  disclaimer: {
    title: 'Product Disclaimer',
    'content-a': `Agora Live ("this product") is a product provided by Agora. Agora enjoys the copyright and ownership of this product. It is hereby granted free of charge to anyone who obtains a copy of this product and related documentation (hereinafter referred to as "software") to try the software without limitation, including but not limited to trial, copy, modify, merge, publish, distribute, but this product shall not be used For any commercial use, you may not sublicense and / or sell copies of the software.`,
    'content-b': `This product is provided "as is" without any express warranty, including but not limited to guarantees of suitability, suitability for specific purposes, and non-infringement. Whether it is due to any contract, infringement or other forms of conduct related to this product or the trial of this product or other methods, Agora will not be responsible for any claims, damages or other liabilities.`,
    'content-c': `You are free to choose whether to try the services provided by this product. If you download, install, or try the services provided in this product, it means that you trust the owner of the product, and Agora shall not be responsible for any form of loss or injury caused by yourself or others when you try the services provided in this product for any reason.`,
  },
  confirm: {
    delete: 'Delete prompt',
  },
  stream: {
    'placeholder.loading': 'Camera is loading',
    'placeholder.muted': 'Camera is closed',
    'placeholder.broken': 'Camera is broken',
    'placeholder.notpresent.teacher': 'Teacher is not in the classroom',
    'placeholder.notpresent.student': 'Student is not in the classroom',
  },
  screenshare: {
    display: 'Display {reason}',
  },
  toast2: {
    'teacher.turn.off.my.mic': 'You are muted',
    'teacher.turn.on.my.mic': 'You are unmuted',
    'teacher.turn.off.my.cam': 'The teacher has turned off your camera',
    'teacher.turn.on.my.cam': 'The teacher has turned on your camera',
    'teacher.grant.permission': 'You can now annotate on the whiteboard',
    'teacher.revoke.permission': 'Your access to the whiteboard has been revoked by the teacher',
    'teacher.accept.onpodium':
      'You are on stage now, you are in presentation mode now. Please feel free to interact with others',
    'teacher.revoke.onpodium': 'You are off the stage now, you are no longer in presentation mode',
    'teacher.reward': '{reason} has been rewarded by the teacher',
    'teacher.reward2':
      'Congratulations to {reason1} and {reason2} other students for getting a star',
    screen_permission_denied:
      'Before using screen sharing, please turn on the screenshot permission',
    stream_window_full: 'The video window has reached the limitation of {reason}',
    save_success: 'Save successfully',
    save_error: 'Failed to save snapshot of the whiteboard',
    saving: 'Please wait…',
    screen_shot_permission_denied: 'Before using screen shot, please turn on the permission',
  },
  breakout_room: {
    create_prefix: 'Create',
    create_suffix: 'breakout rooms',
    auto: 'Auto',
    manual: 'Manual',
    wait_for_assign1: 'To be assigned {reason} persons',
    wait_for_assign2: ', per group {reason} persons',
    wait_for_assign3: 'Per group {reason} persons',
    create_submit: 'Create',
    cancel_submit: 'Cancel',
    assign: 'Assign',
    re_create: 'Re-Create',
    add_group: 'Add a group',
    start: 'Start',
    move_to: 'Move to',
    change_to: 'Change to',
    group_label: 'Group',
    stop: 'Stop Discussion',
    rename: 'Rename',
    remove: 'Remove',
    not_grouped: 'Not grouped',
    confirm_invite_teacher_content: '{reason2} in Room {reason1} asked for help',
    confirm_invite_student_btn_ok: 'Join',
    confirm_invite_student_btn_cancel: 'Later',
    confirm_ask_for_help_absent_content: 'Teacher is not in this classroom',
    confirm_ask_for_help_btn_cancel: 'Cancel',
    already_in_room: 'You are already in this group',
    not_accepted: 'Not accepted',
    joined: 'Joined',
    student: 'Student',
    broadcast_message: 'Send to all',
    send: 'Send',
    cancel: 'Cancel',
    broadcast_message_success: 'Message sent successfully',
    broadcast_message_cannot_be_empty: 'Message cannot be empty',
    group_is_full: 'Group is full of {reason}',
    confirm_stop_group_title: 'Stop Discussion',
    confirm_stop_group_content:
      'Do you want to close all breakout rooms? After closing all breakout rooms, all the students will be returned to the main room',
    confirm_stop_group_sure: 'End',
    confirm_delete_group_title: 'Delete Group',
    confirm_delete_group_content: 'Are you sure you want to delete the {reason} group ?',
    confirm_join_group_title: 'Join Group',
    confirm_join_group_content: 'Are you sure you want to join the {reason}?',
    send_to_all_placeholder: 'This is a general message, 300 words Max',
    create_group: 'Create Breakout Room',
    group_number: 'Breakout Rooms',
    group_type: 'Attendees',
    group_tips: 'Copy classroom content to group',
    user_panel_empty: 'Empty',
    group_current_has_students: '{reason}',
    group_current_empty: 'Empty',
  },
  /** Breakout Room  */
  fcr_group_help_title: 'Request help',
  fcr_group_help_content: 'You can invite the teacher to this group for assistance.',
  fcr_group_help_teacher_busy_msg:
    'The teacher is currently helping others. Please try again later.',
  fcr_group_teacher_is_helping_others_msg:
    'The teacher is helping other group, Please wait for minutes.',
  fcr_group_teacher_exist_hint: 'The teacher is already in the group',
  fcr_group_invite: 'Invite',
  fcr_group_invitation: '	Teacher is inviting you to join {reason}',
  fcr_group_button_join: 'Join',
  fcr_group_button_later: 'Later',
  fcr_group_joining: 'Joining {reason}',
  fcr_group_join: 'Join group',
  fcr_group_enter_welcome: 'Welcome to join {reason} and discuss with everyone',
  fcr_group_enter_group: '{reason1} {reason2} has joined group',
  fcr_group_exit_group: '{reason1} {reason2} has left group',
  fcr_group_close_group: 'The teacher closed breakout rooms',
  fcr_group_invite_back_main_room: 'The teacher is inviting you to return to main session',
  fcr_group_back_main_room: 'Returning to main session...',
  fcr_group_back_sure: 'Sure',
  fcr_group_back_cancel: 'Cancel',
  fcr_group_back_exit: 'Exit',
  fcr_group_back_to_main_room: 'Return to main session',
  fcr_group_exit_room: 'Leave Room',
  fcr_group_student_not_in_room: 'The user didn‘t enter the group',
  fcr_group_sure: 'Sure',
  /** Breakout Room  */
  /** Remote Control */
  fcr_share_title_teacher: 'Teacher Screen Share',
  fcr_share_title_singel_window: 'Support sharing a single application',
  fcr_share_title_full_screen: 'Support full screen sharing',
  fcr_share_title_sound: 'Audio is not supported',
  fcr_share_title_all_student: 'Student Screen Share',
  fcr_share_title_any_student: 'You can assign a student to share the screen',
  fcr_share_selected: '{reason} Selected',
  fcr_share_sharing: "Sharing {reason}'s screen",
  fcr_share_authorized_control: 'The teacher has authorized you to control the screen',
  fcr_share_forbidden_control: 'The teacher has forbidden your screen control',
  fcr_share_device_not_support: '{reason}‘s device does not support remote control',
  fcr_share_Remote_control_disconnected: '{reason} left classroom，Remote control disconnected',
  fcr_share_reminded_student_agree:
    '{reason1} has not agreed to share his/her screen,reminded {reason2} to click on the "Agree" button to share his/her own screen',
  fcr_share_teacher_requesting_share:
    'The teacher adds to have access to your screen content and remote control your device.Do you want to accept now?',
  fcr_share_stopped_student_share: 'The teacher has stopped viewing your screen',
  fcr_share_no_student: "Can't share student's screen as there's no student in the classroom",
  fcr_share_device_no_support: 'Student devices do not support remote control',
  fcr_rc_control_bar_allow_student_control: 'Allow {reason} to control',
  fcr_rc_control_bar_disallow_student_control: 'Forbid students to control',
  fcr_share_title_select_window_share: 'Select a window to share',
  fcr_share_title_desktop: 'Desktop',
  fcr_share_title_application: 'Application',
  fcr_share_title_share_window: 'Share this window',
  fcr_share_button_agree: 'Agree',
  fcr_share_title_controling: 'Remote controlling',
  fcr_share_switch: 'Switch application',
  fcr_rc_control_anti_virus_software_conflict:
    'If you have trouble accessing the remote control features, please turn off your anti-virus software.',
  fcr_close: 'Close',
  fcr_online_courseware_label_file_type: 'Sharing courseware',
  fcr_online_courseware: 'Online courseware',
  fcr_online_courseware_button_upload_online_file: 'Upload courseware',
  fcr_online_courseware_button_upload: 'Upload',
  fcr_online_courseware_button_close: 'Close',
  fcr_online_courseware_label_link: 'Hyperlink',
  fcr_online_courseware_label_file_name: 'File name',
  fcr_online_courseware_label_uploadpage: 'Upload courseware',
  fcr_please_input: 'Please input',
  fcr_online_courseware_input_content: 'Please input the link and file name',
  fcr_online_courseware_valid_url: 'Please input the correct link',
  fcr_alert_title: 'Prompt',
  fcr_alert_submit: 'OK',
  fcr_alert_cancel: 'Cancel',
  /** Home Settings*/
  settings_setting: 'Settings',
  fcr_settings_option_general: 'General Settings',
  fcr_settings_option_about_us: 'About Us',
  settings_logout: 'Logout',
  settings_logout_alert: 'Are you sure to logout?',
  settings_nickname: 'Nick Name',
  fcr_settings_label_region: 'Region',
  settings_theme: 'Theme',
  settings_theme_light: 'Light',
  settings_theme_dark: 'Dark',
  fcr_settings_label_language: 'Language',
  settings_close_account: 'Close Account',
  fcr_settings_option_general_language_simplified: 'Simplified Chinese',
  fcr_settings_option_general_language_traditional: 'Traditional Chinese',
  fcr_settings_option_general_language_english: 'English',
  fcr_settings_label_about_us_about_us: 'About',
  fcr_settings_link_about_us_privacy_policy: 'Privacy Policy',
  fcr_settings_link_about_us_user_agreement: 'Terms of Service',
  fcr_settings_label_about_us_fcr_ver: 'Flexible Classroom Version',
  fcr_settings_label_about_us_sdk_ver: 'SDK Version',
  settings_disclaimer: 'Product Disclaimer',
  settings_register: 'Sign up Agora.io',
  settings_publish_time: 'Version Time',
  settings_logoff_detail: {
    1: 'Unfortunately,Flexible Classroom is not able to continue serving you.Thank you.Delete your account will result in …',
    2: '1.Delete the room data associated with the account.',
    3: '2.delete account and mobile.',
    4: 'I have read and confirmed to delete my account.',
  },
  settings_logoff_agreenment: 'I have read and confirm the cancellation of account',
  settings_logoff_submit: 'Confirm',
  settings_logoff_alert: 'Are you sure to delete your account?',
  fcr_vocational_teacher_absent: 'The teacher is not in the classroom',
  fcr_vocational_video_start_early_alert:
    'The lesson video will be played immediately in advance, is it confirmed?',
  /** Remote Control */
  begin_class: 'Begin class',
  edu_error: {
    '600000': 'Failed to join the classroom',
    '600001': 'Failed to join the classroom',
    '600002': 'Failed to validate extension, upload',
    '600003': 'Failed to upload: file format not supported',
    '600004': 'Failed to upload file to storage',
    '600005': 'Failed to upload file',
    '600006': 'Whiteboard not available',
    '600007': 'Whiteboard not available',
    '600008': 'Whiteboard not available',
    '600009': 'Failed to close whiteboard',
    '600010': 'Whiteboard not available',
    '600011': 'Whiteboard not available',
    '600012': 'Unsupported file format',
    '600013': 'Classroom not available',
    '600014': 'Failed to kick out',
    '600015': 'Local user information not obtained',
    '600016': 'Failed to get off the podium',
    '600017': 'Failed to reject hand up',
    '600018': 'Failed cancel hand up',
    '600019': 'Failed to start carousel ',
    '600020': 'Failed to stop carousel',
    '600021': 'Failed to mute',
    '600022': 'Failed to close widget',
    '600023': 'Failed to accept hand up',
    '600024': 'Failed to hand up',
    '600025': 'Failed to close widget',
    '600026': 'Data error',
    '600027': 'Failed to send reward',
    '600028': 'Failed to enable video',
    '600029': 'Failed to disable video',
    '600030': 'Failed to toggle video',
    '600031': 'Failed to enable audio',
    '600032': 'Failed to disable audio',
    '600033': 'Failed to toggle audio',
    '600034': 'Failed to load whiteboard',
    '600035': 'Failed to start recording',
    '600036': 'Failed to stop recording',
    '600037': 'Failed to join RTC',
    '600038': 'Failed to leave RTC',
    '600039': 'Failed to load whiteboard',
    '600040': 'Failed to leave whiteboard',
    '600041': 'Invalid to classroom state',
    '600042': 'Invalid to RTC state',
    '600043': 'Invalid to whiteboard state',
    '600044': 'Failed to leave the classroom',
    '600045': 'RTE uninitialized',
    '600046': 'Failed to hand up',
    '600047': 'Whitboard unavailable',
    '600048': 'Failed to get history chat message',
    '600049': 'Failed to get history chat message',
    '600050': 'Failed to get conversation list',
    '600051': 'Failed to send message',
    '600052': 'Failed to send message',
    '600053': 'Failed to mute users',
    '600054': 'Failed to unmute users',
    '600055': 'Device manager not initialized',
    '600056': 'Invalid students number',
    '600057': 'Failed to delete cloud resource',
    '600058': 'Failed to load cloud resources',
    '600059': 'Failed to update classroom state',
    '600060': 'Failed to start screen share',
    '600061': 'Failed to stop screen share',
    '600062': 'Failed to update local device state',
    '600063': 'Failed to update remote device state',
    '600064': 'Failed to upload file to cloud resource',
    '600065': 'Failed to update ExtApp properties',
    '600066': 'Failed to update ExtApp properties',
    '600067': 'Failed to convert cloud resource',
    '600068': 'The resource is converting',
    '600069': 'Failed to get all students off the podium',
    '600070': 'Failed to update Whiteboard state',
    '600071': 'Classroom state not initialized',
    '600072': 'Whiteboard connection timeout',
    '600073': 'Failed to report information',
    '600074': 'The resource is already opened',
    '600075': 'Failed to get on stage',
    '600077': 'Failed to get upload checkpoint',
    '600078': 'Failed to switch stream type',
    '600079': 'Failed to enable dual stream',
    '600080': 'Failed to set low stream parameter',
    '600090': 'Failed to join rdc room',
  },
  edu_serv_error: {
    '20400200': 'UserUuid is required!',
    '20400300': 'Stream is required!',
    '20401000': 'User token invalid!',
    '20401001': 'Role cannot join room!',
    '20403001': 'This role is full in the room!',
    '20403002': 'Room is full!',
    '20404000': 'Process not exist!',
    '20404100': 'Room not exist!',
    '20410101': 'Sequence is obsolete!',
    '20404200': 'User not exist!',
    '20404300': 'Stream not exist!',
    '20404400': 'Room template not exist!',
    '20409000': 'Process conflict!',
    '20409100': 'Room conflict!',
    '20409300': 'Stream uuid conflict!',
    '20410100': 'Room is end!',
    '20410200': 'User not online!',
    '20500300': 'Create stream failed!',
    '20500001': 'Generate token failed!',
    '30403100': 'You cannot join room.',
    '30400420': 'Please set whiteboard token in Agora console.',
    '30403200': 'You cannot send chat message.',
    '30404200': 'The teacher is not in the room.',
    '30409100': 'Session is started.',
    '30409101': 'Session is ended.',
    '30409102': 'Screen has shared.',
    '30409103': 'Screen has not shared.',
    '30409104': 'roomType conflicts.',
    '30409410': 'Record is not started.',
    '30409411': 'Record is running.',
    '30400412': 'Param "url" or "rootUrl" is required in web mode.',
    '30500420': 'Whiteboard failed to create room.',
    '30409440': 'Reward reached room limit.',
    '30409430': 'Operate conflict.',
    '30404430': 'Private speech not found.',
    '30404460': 'process not found.',
    '30404461': 'progress not found.',
    '30409460': 'progress conflict.',
    '30404462': 'accept not found.',
    '30410460': 'process unable.',
    '30429460': 'progress reached max wait.',
    '30429461': 'accept reached max count.',
    '30409601': 'user is being invited',
  },
  marketing: {
    title: 'Coupon',
    search: 'Search',
    table: {
      name: 'Name',
      role: 'Role',
      loading: 'Loading More...',
      end: 'No More',
      role_teacher: 'Teacher',
      role_student: 'Student',
      role_assistant: 'Assistant',
      role_audience: 'Audience',
    },
    footer: {
      discount: 'Discount',
      unit: 'RMB',
      send: 'Send',
      errorMsg: 'Can only enter the Numbers',
    },
    receive: {
      ok: 'To Use',
      cancel: 'Cancel',
      title: 'Congratulations',
      context: 'Click "To Use".Jump to product link',
      coupon: 'Coupon',
      unit: 'RMB',
    },
    send: {
      success: 'Send coupons successfully',
      fail: 'Send coupons failure',
    },
  },
  invite: {
    title: 'Invite On Podium',
    clear_podium: 'Off Podium',
    accept_podium: 'Allow',
    inviting_podium: 'Inviting',
    invite_podium: 'Invite',
    confirm: {
      title: 'Prompt',
      content:
        'The teacher invited you to power exchange, click ok to power click cancel to ignore',
      ok: 'OK',
      cancel: 'Cancel',
    },
  },
  vocational: {
    handsUp: 'Hands up',
    handsUpReviewing: 'Reviewing',
    offPodium: 'Off podium',
  },
  question: 'Question',
  fcr_copy_title: 'Share',

  fcr_copy_room_name: 'Room Name:',
  fcr_copy_share_link: 'Invite Link:',
  fcr_copy_share_link_copy: 'Copy link',
  fcr_copy_success: 'Copy success',
};
