export const zhHK = {
  'Close Microphone': '禁用麥克風',
  'Open Microphone': '開啟麥克風',
  'Camera Not Available': '攝像頭已禁用',
  'Microphone Not Available': '麥克風已禁用',
  'Close Camera': '禁用攝像頭',
  'Open Camera': '開啟攝像頭',
  'Clear Podium': '下台',
  'Clear Podiums': '全體下台',
  'Close Whiteboard': '取消授權白板',
  'Open Whiteboard': '授權白板',
  Star: '獎勵',
  'Open Private Call': '開啟私密語音',
  'Close Private Call': '關閉私密語音',
  role: {
    teacher: '老師',
    student: '學生',
    assistant: '助教',
  },
  disabled: '禁用',
  whiteboard: {
    'upload-success': '上傳成功',
    'upload-error': '上傳異常',
    converting: '轉換中',
    'disconnect-img-alt': '白板未連接',
    'disconnect-btn': '重新連接',
    'courseWare-loading': '課件加載中,請稍候…',
    'h5-courseWare': 'H5課件',
    'test-courseWare': 'test課件',
    'clear-whiteboard': '你想清空白板內容嗎？',
  },
  screen_share: '屏幕共享',
  kick: {
    kick_out_student: '移出學生',
  },
  radio: {
    kicked_once: '僅移出教室一次',
    ban: '禁止再次進入教室',
  },
  course: {
    pre_class: '課前',
    in_class: '已上課',
    end_class: '課程已結束',
    join_failed: '加入失敗',
    screen_sharing: '屏幕共享',
  },
  device: {
    camera: '攝像頭',
    microphone: '麥克風',
    speaker: '揚聲器',
    microphone_volume: '麦克风音量',
    speaker_volume: '揚聲器音量',
  },
  student: {
    student_name: '學生姓名',
    camera: '攝像頭',
    microphone: '麥克風',
    operation: '踢人',
  },
  roster: {
    chat: '禁言',
    teacher_name: '教師姓名:',
    user_list: '花名冊',
    student_name: '姓名',
    student_co_video: '上下台',
    close_student_co_video: '你已下台,暫時不能進行互動了喔',
    open_student_co_video: '你已被老師邀請上台,請積極互動喔',
    board_state: '學生授權',
    camera_state: '攝像頭',
    microphone_state: '麥克風',
    reward: '獎勵',
    kick: '踢人',
    granted: '授權',
    shift: '開啟',
    everyone: '全部',
    available: '非禁用',
    students_in: '學生',
    sequence: '順序',
    random: '隨機',
    order_every: '輪播',
    seconds: '秒',
    no_more_data: '沒有更多數據了',
  },
  hands_up: '舉手',
  on_podium_max_count: '上台人數已達上限,無法繼續邀請學生上台',
  hands_up_tip: '舉手請長按',
  co_video: {
    remote_open_camera: '攝像頭已打開',
    remote_open_microphone: '你可以發言了',
    remote_grant_board: '你可以使用白板了',
    remote_close_camera: '攝像頭已關閉',
    remote_close_microphone: '你暫時不能發言了',
    remote_revoke_board: '你現在無權使用白板',
    received_student_hands_up: '有學生舉手了',
    received_teacher_accepted: '老師已同意上台',
    received_teacher_refused: '老師拒絕了上台',
    received_student_cancel: '學生取消了舉手',
    received_message_timeout: '消息未響應,請重新嘗試',
    hands_up_requsted: '發送舉手申請成功',
    hands_up_cancelled: '舉手申請已取消',
  },
  private_media_chat: {
    chat_started: '私密聊天開始',
    chat_ended: '私密聊天結束',
  },
  placeholder: {
    muted_chat: '禁言中',
    empty_chat: '還沒有消息',
    empty_quiz: '暫無提問',
    enable_chat_muted: '已開啟學生禁言',
    input_message: '請輸入消息',
    loading: '加載中',
    wait_student: '等待學生進入教室',
    wait_teacher: '外教已離開教室',
  },
  signal: {
    delay: '網絡延遲',
    lose: '丟包率',
    status: '網絡狀態',
    CPU: 'CPU',
    receive: '收到',
    send: '發出',
  },
  error: {
    banned: '禁止進入',
    cannot_join: '你已被禁止進入這個教室！',
    not_found: '頁面找不到',
    apply_co_video_limit: '舉手超出連麥人數限制',
    send_co_video_limit: '點名超出連麥人數限制',
    components: {
      paramsEmpty: '參數:{reason}不能為空',
    },
    class_end: '課程已結束,請點擊確定離開教室',
    unknown: '發生未知錯誤,錯誤代碼: {errCode}, 信息: {message}',
    room_is_full: '當前房間已滿,請點擊確認離開教室',
    network_timeout: '網絡請求超時',
  },
  toast: {
    mute_chat: '你已被老師禁言了',
    unmute_chat: '你被解除禁言了',
    remote_mute_chat: '{studentName}被老師禁言了',
    remote_unmute_chat: '{studentName}被老師解除禁言了',
    add_screen_share: '老師開啟了屏幕共享',
    remove_screen_share: '老師關閉了屏幕共享',
    granted_board_success: '授權白板成功',
    revoke_board_success: '收回白板成功',
    create_screen_share_failed: '創建屏幕共享失敗',
    kick_by_other_side: '遠端重複登錄, 當前帳號已離開房間',
    screen_share: '屏幕共享',
    close_ppt: '關閉當前課件',
    sure_close_ppt: '你確定要關閉嗎？',
    end_class: '課程已結束',
    quit_from_room: '離開教室',
    kick_by_teacher: '你已被踢出教室',
    upload_log_failure: '上傳日誌失敗,錯誤類型:{reason}, 詳情參考開發者工具',
    show_log_id: `請提供你的日誌ID: {no}`,
    api_login_failured: '房間加入失敗, 原因: {reason}',
    confirm: '確定',
    cancel: '取消',
    leave_room: '離開教室',
    quit_room: '是否確定要退出教室？',
    kick: '遠端重複登錄, 當前帳號已離開房間',
    login_failure: '登陸房間失敗',
    whiteboard_lock: '設置白板跟隨',
    whiteboard_unlock: '取消白板跟隨',
    canceled_screen_share: '已取消屏幕共享',
    screen_sharing_failed: '屏幕共享失敗, 原因:{reason}',
    recording_failed: '開啟雲錄製失敗, 原因:{reason}',
    start_recording: {
      title: '錄製提示',
      body: '你確定要開啟錄製嗎?',
      success: '錄製開啟成功',
    },
    stop_recording: {
      title: '停止錄製',
      body: '你確定要停止錄製嗎?',
      success: '錄製停止成功',
    },
    recording_too_short: '錄製太短,至少15秒',
    rtm_login_failed: '房間登陸失敗, 請檢查網絡設置',
    rtm_login_failed_reason: '房間登陸失敗, 原因: {reason}',
    replay_failed: '回放失敗,請刷新頁面重試',
    teacher_exists: '該房間老師已存在,請等待30秒或重新創建教室',
    student_over_limit: '超出學生最大人數,請等待30秒或重新創建教室',
    teacher_and_student_over_limit: '超出學生和老師的最大人數',
    teacher_accept_whiteboard: '老師已授權了你白板的權限',
    teacher_cancel_whiteboard: '老師已收回了你白板的權限',
    teacher_accept_co_video: '老師已允許連麥',
    teacher_reject_co_video: '老師已拒絕連麥',
    teacher_cancel_co_video: '老師已取消連麥',
    student_cancel_co_video: '學生已取消連麥',
    student_send_co_video_apply: '"{reason}" 學生發起了連麥申請',
    student_peer_leave: '"{reason}" 離開了',
    stop_co_video: '教師停止了"{reason}"的連麥',
    reject_co_video: '您取消了學生的連麥申請',
    close_co_video: '您關閉了學生的連麥',
    close_youself_co_video: '你關閉了自己的連麥',
    accept_co_video: '您同意了連麥',
    successfully_joined_the_room: '加入房間成功',
    failed_to_join_the_room: '加入房間失敗',
    failed_to_authorize_whiteboard: '授權白板失敗',
    failed_to_deauthorize_whiteboard: '取消授權白板失敗',
    failed_to_query_playback_list: '查詢回放列表失敗',
    audio_equipment_has_changed: '音頻設備發生了變化',
    video_equipment_has_changed: '視頻設備發生了變化',
    failed_to_initiate_screen_sharing: '發起屏幕共享失敗',
    failed_to_end_screen_sharing: '結束屏幕共享失敗',
    failed_to_initiate_screen_sharing_to_remote: '向遠端發起屏幕共享失敗',
    failed_to_enable_screen_sharing: '開啟屏幕共享失敗',
    failed_to_enable_screen_sharing_permission_denied: '開啟屏幕共享失敗！請先授權屏幕共享權限！',
    failed_to_send_chat: '發送聊天失敗',
    failed_to_translate_chat: '翻譯聊天失敗',
    failed_to_send_reward: '發送獎勵失敗',
    failed_to_join_rtc_please_refresh_and_try_again: '加入rtc失敗,請刷新重試',
    leave_rtc_channel: '離開rtc頻道',
    failed_to_leave_rtc: '離開rtc失敗',
    co_video_close_success: '下麥成功',
    co_video_close_failed: '下麥失敗',
    publish_rtc_success: '發布RTC成功',
    open_whiteboard_follow: '打開白板跟隨',
    close_whiteboard_follow: '關閉白板跟隨',
    i: '我',
    teacher: '老師',
    the_teacher_authorized_your_whiteboard: '老師授權了你的白板',
    the_teacher_cancelled_your_whiteboard_permission: '老師取消了你的白板權限',
    publish_business_flow_successfully: '發布業物流成功',
    media_method_call_failed: '媒體方法調用失敗',
    successfully_left_the_business_channel: '離開業務頻道成功',
    course_started_successfully: '課程開始成功',
    setting_start_failed: '設置開始失敗',
    the_course_ends_successfully: '課程結束成功',
    setting_ended_failed: '設置結束失敗',
    start_recording_successfully: '開始錄製成功',
    start_recording_failed: '開始錄製失敗',
    successfully_ended_recording: '結束錄製成功',
    failed_to_end_recording: '結束錄製失敗',
    you_have_a_default_message: '你有一條默認消息',
    the_teacher_agreed: '老師同意了',
    student_applied: '學生申請了',
    you_were_dismissed_by_the_teacher: '你被老師下麥了',
    student_canceled: '學生取消了',
    the_teacher_refused: '老师拒絕了',
    failed_to_initiate_a_raise_of_hand_application: '發起舉手申請失敗',
    failed_to_end_the_call: '結束通話失敗',
    failed_to_join_board: '加入白板失敗',
    stop_screen_share_failed: '停止屏幕共享失敗',
    classroom_remote_join: '帳號在遠端設備登陸,您已離開教室',
    time_interval_between_start: `距離上課開始還有: {reason}分鐘`,
    time_interval_between_end: `課程還有{reason}分鐘結束`,
    class_is_end: `下課咯,教室還有{reason}分鐘關閉`,
    time_interval_between_close: `教室還有{reason}分鐘關閉`,
    reward_limit: '獎杯已全部發完',
    chat_enable: '禁言模式開啟',
    chat_disable: '禁言模式關閉',
    upload_failure: '上傳失敗',
    download_success: '下載成功',
    download_failure: '下載失敗',
    resource_already_opened: '課件已經打開',
    resource_is_converting: '課件正在轉換中',
    fail_to_convert_resource: '文件轉化失敗',
    interaction_too_frequent: '操作過於頻繁,請稍候再試',
  },
  end_class_confirm: '確定要結束教室嗎？',
  notice: {
    student_interactive_apply: `"{reason}"想和你連麥`,
  },
  scaffold: {
    clear: '清屏',
    undo: '撤銷上一步操作',
    redo: '重做',
    search: '搜索',
    student_list: '學生列表',
    pencil: '畫筆',
    laser_pointer: '激光筆',
    countdown: '倒計時',
    straight: '直線',
    circle: '圓圈',
    rectangle: '矩形',
    arrow: '箭頭',
    pentagram: '五角形',
    rhombus: '菱形',
    triangle: '三角形',
    clicker: '鼠標',
    selector: '選擇',
    eraser: '橡皮擦',
    color: '顏色',
    blank_page: '新增一頁',
    move: '移動工具',
    follow: '跟隨模式',
    un_follow: '解除跟隨',
    screen_share: '屏幕共享',
    stop_screen_share: '停止共享',
    cloud_storage: '雲盤',
    text: '文本',
    tools: '工具欄',
    user_list: '用戶列表',
  },
  cloud: {
    fileName: '文件名',
    size: '大小',
    progress: '進度條',
    operation: '操作',
    updated_at: '修改時間',
    publicResources: '公共資源',
    deleteTip: '確認刪除所選文件嗎？',
    personalResources: '我的資源',
    downloadResources: '下載資源',
    upload: '上傳',
    delete: '刪除',
    download: '下載',
    downloading: '下載中',
    pause: '暫停',
    upload_success: '上傳成功',
    supprotTypeTitle: '教室內支持的文件格式',
    fileType: '格式類型',
    ppt: 'Powerpoint演示文檔',
    word: 'Word文檔',
    excel: 'Excel文檔',
    pdf: 'Pdf文檔',
    video: '視頻',
    audio: '音頻',
    txt: '文本文檔',
    photo: '圖片',
    fileCounts: '共{fileCounts}項',
  },
  media: {
    camera: '攝像頭',
    switch_camera: '切換攝像頭',
    microphone: '麥克風',
    switch_microphone: '切換麥克風',
    microphone_volume: '麥克風音量',
    speaker: '揚聲器',
    switch_speaker: '切換揚聲器',
    volume: '音量',
    adjust_volume: '調整音量',
    test_speaker: '檢測揚聲器',
    camera_error: '監視器被拔出或監視器已佔用,無法顯示視頻！',
    microphone_error: '麥克風被拔出或麥克風被佔用,無法使用麥克風！',
    mirror: '鏡像模式',
    beauty: '美顏',
    whitening: '美白',
    buffing: '磨皮',
    ruddy: '紅潤',
    default: '默認',
  },
  pretest: {
    title: '設備檢測',
    settingTitle: '設備設定',
    finishTest: '完成',
    detect_new_device: '檢測到新設備,請使用！',
    camera_move_out: '監視器被拔出,無法顯示視頻！',
    mic_move_out: '麥克風被拔出！',
    playback_move_out: '揚聲器被拔出！',
    device_move_out: '設備被拔出！',
    device_not_working: '設備未正常工作！',
    detect_new_device_in_room: '檢測到新設備,請點擊“設定”後,選擇新設備。',
    teacher_device_may_not_work: '老師視頻可能出現問題！',
  },
  'biz-header': {
    perf: 'Perf',
    setting: '設定',
    exit: '退出',
    recording: '錄製中',
    start_record: '開啟錄製',
    stop_record: '停止錄製',
  },
  message: '消息',
  quiz: '提問',
  zh: '中文',
  nav: {
    delay: '延遲:',
    network: '網絡:',
    cpu: 'CPU: ',
    class_end: '課程結束',
    class_start: '課程開始',
    back: '返回',
    to_start_in: '距離上課還有:',
    started_elapse: '已上課:',
    ended_elapse: '已下課:',
    class_not_started: '課程未開始',
    hours: '小時',
    minutes: '分鐘',
    seconds: '秒',
    ms: '毫秒',
    short: {
      hours: '小時',
      minutes: '分鐘',
      seconds: '秒',
    },
    signal_excellent: '優',
    signal_good: '良',
    signal_weak: '良',
    signal_bad: '差',
    signal_unknown: '未知',
    signal_down: '斷網',
    singal_poor_tip: '當前網絡質量不佳,請檢查設備網絡連接',
    singal_down_tip: '當前網絡已斷開,請檢查設備網絡連接',
  },
  tool: {
    board_name: '白板',
    screen_share: '荧幕共亯',
    selector: '滑鼠選擇器',
    pencil: '畫筆',
    rectangle: '矩形',
    ellipse: '橢圓',
    eraser: '橡皮擦',
    text: '文字',
    color_picker: '調色板',
    add: '新增一頁',
    upload: '上傳',
    hand_tool: '手抓工具',
    extension_tool: '擴展',
    clear: '清除',
    disk: '雲盤',
    prev: '後退',
    next: '前進',
    zoomIn: '放大',
    zoomOut: '縮小',
    fullScreen: '全屏',
    reduction: '還原',
    reset: '居中',
  },
  send: '發送',
  home: {
    form_title: '免費試用',
    roomId: 'roomId',
    roomId_placeholder: '請輸入roomId',
    userId: 'userId',
    userId_placeholder: '請輸入userId',
    roomName: '房間',
    roomName_placeholder: '請輸入房間名',
    nickName: '昵稱',
    nickName_placeholder: '請輸入昵稱',
    roomType: '類型',
    roomType_placeholder: '請選擇課堂類型',
    roomType_1v1: '1對1',
    roomType_interactiveSmallClass: '互動小班課',
    roomType_interactiveBigClass: '大班課',
    role: '角色',
    role_placeholder: '請選擇你的角色',
    encryptionMode: '模式',
    encryptionMode_placeholder: '請選擇加密模式',
    encryptionKey: '密匙',
    encryptionKey_placeholder: '請輸入金鑰',
    role_teacher: '老師',
    role_student: '學生',
    role_assistant: '助教',
    role_audience: '觀眾',
    role_observer: '監課',
    language: '語言:',
    language_placeholder: '請選擇語言',
    duration: '時長',
    duration_unit: '分鐘',
    enter_classroom: '進入教室',
    region_placeholder: '請選擇區域',
    region: '區域:',
    'header-left-title': '聲網靈動課堂',
    about: '關於',
    'input-error-msg': '只能輸入6-50比特字元（字母、數位）',
    'input-username-error-msg': '只能輸入3-25比特字元（文字、字母、數位、空格）',
    network_error: '當前網絡异常,請稍後再試',
    'recordation-search': '課程重播',
    'recordation-tip': '只能査詢1小時內的重播',
    replay: '重播',
    search: '査詢',
    system_name: '聲網靈動課堂',
  },
  'home-about': {
    'privacy-policy': '隱私條例',
    'product-disclaimer': '免責聲明',
    'sign-up': '注册聲網帳號',
    'version-time': '發版時間',
    'sdk-version': 'SDK版本',
    'classroom-version': '靈動課堂版本',
    check: '查看',
    register: '注册',
  },
  disclaimer: {
    title: '免責聲明',
    'content-a': `靈動課堂（“本產品”）是由上海兆言網絡科技有限公司（“上海兆言”）提供的一款測試產品,上海兆言享有本產品的著作權和所有權。 特此免費授予獲得本產品和相關文檔檔案（以下簡稱“軟件”）副本的任何人無限制地使用軟件的權利,包括但不限於使用,複製,修改,合併,發佈,分發,但本產品不得用於任何商業用途,不得再許可和/或出售該軟件的副本。`,
    'content-b': `本產品按“現狀”提供,沒有任何形式的明示擔保,包括但不限於對適配性、特定目的的適用性和非侵權性的擔保。 無論是由於與本產品或本產品的使用或其他管道有關的任何契约、侵權或其他形式的行為,上海兆言均不對任何索賠、損害或其他責任負責。`,
    'content-c': `您可以自由選擇是否使用本產品提供的服務,如果您下載、安裝、使用本產品中所提供的服務,即表明您信任該產品所有人,上海兆言對任何原因在使用本產品中提供的服務時可能對您自身或他人造成的任何形式的損失和傷害不承擔任何責任。`,
  },
  countdown: {
    appName: '倒計時',
    seconds: '秒',
    start: '開始',
    restart: '重新開始',
  },
  confirm: {
    delete: '刪除提示',
    clear: '清屏提示',
  },
  stream: {
    'placeholder.loading': '正在打開監視器',
    'placeholder.muted': '監視器關閉',
    'placeholder.broken': '監視器損壞',
    'placeholder.notpresent.teacher': '老師不在教室',
    'placeholder.notpresent.student': '學生不在教室',
  },
  screenshare: {
    display: '荧幕{reason}',
  },
  toast2: {
    'teacher.turn.off.my.mic': '老師已關閉你的麥克風,你暫時不能發言了',
    'teacher.turn.on.my.mic': '老師已打開你的麥克風,你可以開始發言了',
    'teacher.turn.off.my.cam': '老師已關閉你的監視器',
    'teacher.turn.on.my.cam': '老師已打開你的監視器',
    'teacher.grant.permission': '你已被老師授權,請使用白板工具互動',
    'teacher.revoke.permission': '你已被老師收回授權,無法使用白板工具互動',
    'teacher.accept.onpodium': '老師邀請你上臺了,與大家積極互動吧',
    'teacher.revoke.onpodium': '你離開講臺了,暫時無法與大家互動',
    'teacher.reward': '祝賀{reason}獲得獎勵',
    'teacher.reward2': '祝賀{reason1}等{reason2}比特同學獲得獎勵',
    screen_permission_denied: '使用荧幕共亯前,請先打開荧幕錄製許可權',
  },
  cabinet: {
    answer: {
      appName: '答題器',
    },
    countdown: {
      appName: '計時器',
    },
    vote: {
      appName: '投票器',
    },
  },
  answer: {
    appName: '答題器',
    start: '開始答題',
    submit: '提交答案',
    change: '修改答案',
    'number-answered': '已答題人數',
    acc: '正確率',
    'right-key': '正確答案',
    'my-answer': '我的答案',
    over: '結束答題',
    'student-name': '學生姓名',
    'answer-time': '答題用時',
    'selected-answer': '所選答案',
    restart: '重新開始',
  },
  vote: {
    appName: '投票',
    start: '開始投票',
    restart: '重新開始',
    over: '結束投票',
    submit: '投票',
    change: '修改投票',
    'input-tip': '請輸入投票問題',
    'item-tip': '請輸入選項內容',
    'single-sel': '單選',
    'mul-sel': '多選',
  },
  begin_class: '開始上課',
  edu_error: {
    '600000': '房間資源未獲取',
    '600001': '加入房間失敗',
    '600002': '無文件副檔名,上傳失敗',
    '600003': '檔案格式不支持,上傳失敗',
    '600004': '文件上傳阿裡雲失敗',
    '600005': '文件上傳失敗',
    '600006': '白板未獲取',
    '600007': '白板資源未獲取',
    '600008': '白板加入失敗',
    '600009': '白板關閉失敗',
    '600010': '白板API添加失敗',
    '600011': '白板視窗管理不可用',
    '600012': '不支持的檔案格式,不可使用',
    '600013': '教室未準備好',
    '600014': '踢出房間失敗',
    '600015': '本地用戶資訊未獲取',
    '600016': '下臺失敗',
    '600017': '駁回舉手失敗',
    '600018': '取消舉手失敗',
    '600019': '輪播啟動失敗',
    '600020': '輪播停止失敗',
    '600021': '禁言失敗',
    '600022': '組件關閉失敗',
    '600023': '同意上臺失敗',
    '600024': '舉手失敗',
    '600025': '挿件關閉失敗',
    '600026': '數據錯誤',
    '600027': '獎勵發放失敗',
    '600028': '啟用視頻失敗',
    '600029': '禁用視頻失敗',
    '600030': '切換視頻失敗',
    '600031': '啟用音訊失敗',
    '600032': '禁用音訊失敗',
    '600033': '切換音訊失敗',
    '600034': '白板加載失敗',
    '600035': '開始錄製失敗',
    '600036': '結束錄製失敗',
    '600037': '加入RTC頻道失敗',
    '600038': '離開RTC頻道失敗',
    '600039': '加入白板失敗',
    '600040': '離開白板失敗',
    '600041': '無效的教室狀態',
    '600042': '無效的RTC狀態',
    '600043': '無效的白板狀態',
    '600044': '離開教室失敗',
    '600045': 'RTE未初始化',
    '600046': '舉手失敗',
    '600047': '白板不可操作',
    '600048': '獲取聊天記錄失敗',
    '600049': '獲取私聊記錄失敗',
    '600050': '獲取私聊清單',
    '600051': '聊天發送失敗',
    '600052': '聊天發送失敗',
    '600053': '禁言失敗',
    '600054': '解除禁言失敗',
    '600055': '裝置管理員未初始化',
    '600056': '學生數量錯誤',
    '600057': '删除雲盤資源失敗',
    '600058': '加載雲盤資源失敗',
    '600059': '課堂狀態更新失敗',
    '600060': '開啟荧幕共亯失敗',
    '600061': '停止荧幕共亯失敗',
    '600062': '本地設備狀態更新失敗',
    '600063': '遠端設備狀態更新失敗',
    '600064': '文件上傳失敗',
    '600065': 'ExtApp狀態更新失敗',
    '600066': 'ExtApp狀態更新失敗',
    '600067': '課件轉換失敗',
    '600068': '課件正在轉換中',
    '600069': '全員下臺失敗',
    '600070': '白板狀態更新失敗',
    '600071': '教室未初始化',
    '600072': '白板連接超時',
    '600073': '資訊上報失敗',
    '600074': '課件已打開',
    '600075': '上臺失敗',
    '600077': '獲取上傳記錄失敗',
  },
  edu_serv_error: {
    '20400200': '未傳入用戶唯一標識',
    '20400300': '未傳入流資訊',
    '20401000': '用戶Token無效',
    '20401001': '此角色不能加入房間',
    '20403001': '教室內該角色人數已達上限,無法進入',
    '20403002': '房間人數已達上限,無法進入',
    '20404000': '行程不存在',
    '20404100': '房間不存在',
    '20410101': '房間已過期',
    '20404200': '用戶不存在',
    '20404300': '流資訊不存在',
    '20404400': '房間範本不存在',
    '20409000': '行程衝突',
    '20409100': '房間衝突',
    '20409300': '流ID衝突',
    '20410100': '房間已結束',
    '20410200': '用戶不線上',
    '20500300': '流創建失敗',
    '20500001': '生成Token失敗',
    '30403100': '你不能加入教室',
    '30400420': '請去控制台設定白板Token',
    '30403200': '你不能發送聊天資訊',
    '30404200': '老師不在教室',
    '30409100': '課程已開始',
    '30409101': '課程已結束',
    '30409102': '荧幕已共亯',
    '30409103': '荧幕未共亯',
    '30409104': '房間類型衝突',
    '30409410': '錄製未開始',
    '30409411': '錄製運行中',
    '30400412': '參數“url”或“rootUrl”在網頁錄製模式必填',
    '30500420': '白板創建失敗',
    '30409440': '房間獎勵已達上限',
    '30409430': '私人聊天衝突',
    '30404430': '私人聊天未找到',
    '30404460': '舉手功能未配寘',
    '30404461': '學生未舉手',
    '30409460': '學生已拒收',
    '30404462': '該學生未上臺',
    '30410460': '配寘舉手功能未開啟',
    '30429460': '舉手人數到達最大上限',
    '30429461': '上臺到達最大上限',
  },
};
