export const zhHK = {
  role: {
    teacher: '老師',
    student: '學生',
    assistant: '助教',
  },
  disabled: '禁用',
  whiteboard: {
    converting: '轉換中',
    'disconnect-img-alt': '白板未連接',
    'disconnect-btn': '重新連接',
  },
  screen_share: '屏幕共享',
  kick: {
    kick_out_student: '移出學生',
  },
  radio: {
    kicked_once: '僅移出教室一次',
    ban: '禁止再次進入教室',
  },
  course: {
    pre_class: '課前',
    in_class: '已上課',
    end_class: '課程已結束',
    join_failed: '加入失敗',
    screen_sharing: '屏幕共享',
  },
  device: {
    camera: '攝像頭',
    microphone: '麥克風',
    speaker: '揚聲器',
    microphone_volume: '麥克風音量',
    speaker_volume: '揚聲器音量',
  },
  student: {
    student_name: '學生姓名',
    camera: '攝像頭',
    microphone: '麥克風',
    operation: '踢人',
  },
  roster: {
    chat: '禁言',
    teacher_name: '教師姓名：',
    user_list: '人員列表',
    student_name: '姓名',
    student_co_video: '上下台',
    close_student_co_video: '你已下台，暫時不能進行互動了哦',
    open_student_co_video: '你已被老師邀請上台，請積極互動哦',
    board_state: '學生授權',
    camera_state: '攝像頭',
    microphone_state: '麥克風',
    reward: '獎勵',
    kick: '踢人',
    granted: '授權',
    shift: '開啟',
    everyone: '全部',
    available: '非禁用',
    students_in: '學生',
    sequence: '順序',
    random: '隨機',
    order_every: '輪播',
    seconds: '秒',
  },
  hands_up: '舉手',
  hands_up_tip: '舉手請長按',
  co_video: {
    remote_open_camera: '攝像頭已打開',
    remote_open_microphone: '你可以發言了',
    remote_grant_board: '你可以使用白板了',
    remote_close_camera: '攝像頭已關閉',
    remote_close_microphone: '你暫時不能發言了',
    remote_revoke_board: '你現在無權使用白板了',
    received_student_hands_up: '有學生舉手了',
    received_teacher_accepted: '老師已同意上台',
    received_teacher_refused: '老師拒絕了上台',
    received_student_cancel: '學生取消了舉手',
    received_message_timeout: '消息未響應，請重新嘗試',
    hands_up_requsted: '發送舉手申請成功',
    hands_up_cancelled: '舉手申請已取消',
  },
  private_media_chat: {
    chat_started: '私密聊天開始',
    chat_ended: '私密聊天結束',
  },
  placeholder: {
    muted_chat: '禁言中',
    empty_chat: '還沒有消息',
    empty_quiz: '暫無提問',
    enable_chat_muted: '已開啟學生禁言',
    input_message: '請輸入消息',
  },
  signal: {
    delay: '網絡延遲',
    lose: '丟包率',
    status: '網絡狀態',
    CPU: 'CPU',
  },
  error: {
    banned: '禁止進入',
    cannot_join: '你已被禁止進入這個教室！ ',
    not_found: '頁面找不到',
    apply_co_video_limit: '舉手超出連麥人數限制',
    send_co_video_limit: '點名超出連麥人數限制',
    components: {
      paramsEmpty: '參數：{reason}不能為空',
    },
    class_end: '課程已結束，請點擊確定離開教室',
    unknown: '發生未知錯誤，錯誤代碼: {errCode}, 信息: {message}',
    room_is_full: '當前房間已滿，請點擊確認離開教室',
  },
  toast: {
    mute_chat: '你已被老師禁言了',
    unmute_chat: '你被解除禁言了',
    remote_mute_chat: '{studentName}被老師禁言了',
    remote_unmute_chat: '{studentName}被老師解除禁言了',
    add_screen_share: '老師開啟了屏幕共享',
    remove_screen_share: '老師關閉了屏幕共享',
    granted_board_success: '授權白板成功',
    revoke_board_success: '收回白板成功',
    create_screen_share_failed: '創建屏幕分享失敗',
    kick_by_other_side: '被其他端踢出',
    screen_share: '屏幕共享',
    close_ppt: '關閉當前課件',
    sure_close_ppt: '你確定要關閉嗎？ ',
    end_class: '課程已結束',
    quit_from_room: '離開教室',
    kick_by_teacher: '你已被踢出教室',
    upload_log_failure: '上傳日誌失敗，錯誤類型：{reason}, 詳情參考開發者工具',
    show_log_id: `請提供你的日誌ID: {no}`,
    api_login_failured: '房間加入失敗, 原因: {reason}',
    confirm: '確定',
    cancel: '取消',
    leave_room: '離開教室',
    quit_room: '確定退出課程嗎？ ',
    kick: '其他端登錄，被踢出房間',
    login_failure: '登錄房間失敗',
    whiteboard_lock: '設置白板跟隨',
    whiteboard_unlock: '取消白板跟隨',
    canceled_screen_share: '已取消屏幕共享',
    screen_sharing_failed: '屏幕分享失敗, 原因：{reason}',
    recording_failed: '開啟雲錄製失敗, 原因：{reason}',
    start_recording: {
      title: '錄製提示',
      body: '你確定要開始錄製嗎?',
      success: '錄製開啟成功',
    },
    stop_recording: {
      title: '停止錄製',
      body: '你確定要停止錄製嗎?',
      success: '錄製停止成功',
    },
    recording_too_short: '錄製太短，至少15秒',
    rtm_login_failed: '房間登錄失敗, 請檢查網絡設置',
    rtm_login_failed_reason: '房間登錄失敗, 原因： {reason}',
    replay_failed: '回放失敗，請刷新頁面重試',
    teacher_exists: '該房間老師已存在，請等待30秒或重新創建教室',
    student_over_limit: '超出學生最大人數，請等待30秒或重新創建教室',
    teacher_and_student_over_limit: '超出學生和老師的最大人數',
    teacher_accept_whiteboard: '老師已授權了你白板的權限',
    teacher_cancel_whiteboard: '老師已收回了你白板的權限',
    teacher_accept_co_video: '老師已允許連麥',
    teacher_reject_co_video: '老師已拒絕連麥',
    teacher_cancel_co_video: '老師已取消連麥',
    student_cancel_co_video: '學生已取消連麥',
    student_send_co_video_apply: '"{reason}" 學生髮起了連麥申請',
    student_peer_leave: '"{reason}" 離開了',
    stop_co_video: '教師停止了"{reason}"的連麥',
    reject_co_video: '您取消了學生的連麥申請',
    close_co_video: '您關閉了學生的連麥',
    close_youself_co_video: '你關閉了自己的連麥',
    accept_co_video: '您同意了連麥',
    successfully_joined_the_room: '加入房間成功',
    failed_to_join_the_room: '加入房間失敗',
    failed_to_authorize_whiteboard: '授權白板失敗',
    failed_to_deauthorize_whiteboard: '取消授權白板失敗',
    failed_to_query_playback_list: '查詢回放列表失敗',
    audio_equipment_has_changed: '音頻設備發生了變化',
    video_equipment_has_changed: '視頻設備發生了變化',
    failed_to_initiate_screen_sharing: '發起屏幕共享失敗',
    failed_to_end_screen_sharing: '結束屏幕共享失敗',
    failed_to_initiate_screen_sharing_to_remote: '向遠端發起屏幕共享失敗',
    failed_to_enable_screen_sharing: '開啟屏幕共享失敗',
    failed_to_enable_screen_sharing_permission_denied: '開啟屏幕共享失敗！請先授權屏幕共享權限！ ',
    failed_to_send_chat: '發送聊天失敗',
    failed_to_translate_chat: '翻譯聊天失敗',
    failed_to_send_reward: '發送獎勵失敗',
    failed_to_join_rtc_please_refresh_and_try_again: '加入rtc失敗，請刷新重試',
    leave_rtc_channel: '離開rtc頻道',
    failed_to_leave_rtc: '離開rtc失敗',
    co_video_close_success: '下麥成功',
    co_video_close_failed: '下麥失敗',
    publish_rtc_success: '發布RTC成功',
    open_whiteboard_follow: '打開白板跟隨',
    close_whiteboard_follow: '關閉白板跟隨',
    i: '我',
    teacher: '老師',
    the_teacher_authorized_your_whiteboard: '老師授權了你的白板',
    the_teacher_cancelled_your_whiteboard_permission: '老師取消了你的白板權限',
    publish_business_flow_successfully: '發佈業務流成功',
    media_method_call_failed: '媒體方法調用失敗',
    successfully_left_the_business_channel: '離開業務頻道成功',
    course_started_successfully: '課程開始成功',
    setting_start_failed: '設置開始失敗',
    the_course_ends_successfully: '課程結束成功',
    setting_ended_failed: '設置結束失敗',
    start_recording_successfully: '開始錄製成功',
    start_recording_failed: '開始錄製失敗',
    successfully_ended_recording: '結束錄製成功',
    failed_to_end_recording: '結束錄製失敗',
    you_have_a_default_message: '你有一條默認消息',
    the_teacher_agreed: '老師同意了',
    student_applied: '學生申請了',
    you_were_dismissed_by_the_teacher: '你被老師下麥了',
    student_canceled: '學生取消了',
    the_teacher_refused: '老師拒絕了',
    failed_to_initiate_a_raise_of_hand_application: '發起舉手申請失敗',
    failed_to_end_the_call: '結束通話失敗',
    failed_to_join_board: '加入白板失敗',
    stop_screen_share_failed: '停止屏幕共享失敗',
    classroom_remote_join: '賬號在遠端設備登錄，您已離開教室',
    time_interval_between_start: `距離上課開始還有: {reason}`,
    time_interval_between_end: `課程還有{reason}結束`,
    class_is_end: `下課咯，教室還有{reason}關閉`,
    time_interval_between_close: `教室還有{reason}關閉`,
    reward_limit: '獎杯已全部發完',
    chat_enable: '禁言模式開啟',
    chat_disable: '禁言模式關閉',
    cloud_resource_conversion_not_finished: '課件正在轉換中，請稍後重試',
    cloud_resource_conversion_not_converted: '課件未轉換成功，如果急用請轉為PDF再上傳使用',
    resource_already_opened: '課件已經打開',
    save_to_cloud_drive: '保存至雲盤',
    save_as: '文件名',
    save_to: '保存至',
    board_restore_fail: '板書加載失敗',
    board_restore_success: '板書加載成功',
    board_save_fail: '板書保存失敗',
    board_save_success: '板書保存成功',
    board_save_fail_empty_name: '請輸入板書草稿名稱',
    board_confirm_clear_state: '確定要清空當前黑板上的內容嗎？ ',
    board_draft_default_name: '板書草稿',
    failed_to_update_extapp_properties: '更新插件狀態失敗',
  },
  end_class_confirm: '確定要結束教室嗎？ ',
  notice: {
    student_interactive_apply: `"{reason}"想和你連麥`,
  },
  scaffold: {
    search: '搜索',
    student_list: '學生列表',
    pencil: '畫筆',
    laser_pointer: '激光筆',
    countdown: '倒計時',
    straight: '直線',
    circle: '圓圈',
    rectangle: '矩形',
    clicker: '鼠標',
    selector: '選擇',
    eraser: '橡皮擦',
    color: '顏色',
    blank_page: '新增一頁',
    move: '移動工具',
    follow: '跟隨模式',
    un_follow: '解除跟隨',
    screen_share: '屏幕共享',
    stop_screen_share: '停止共享',
    cloud_storage: '雲盤',
    text: '文本',
    tools: '工具欄',
    user_list: '用戶列表',
    board_save: '保存板書',
  },
  cloud: {
    fileName: '文件名',
    size: '大小',
    progress: '進度條',
    operation: '操作',
    updated_at: '修改時間',
    publicResources: '公共資源',
    personalResources: '我的資源',
    downloadResources: '預加載資源',
    upload: '上傳',
    delete: '刪除',
    download: '預加載',
    downloading: '下載中',
    pause: '暫停',
    upload_success: '上傳成功',
    upload_failed: '上傳失敗,{reason}',
    search: '搜索',
    prev: '< 上一頁',
    next: '下一頁 >',
    conversion_failed: '資源文件轉換失敗',
  },
  media: {
    camera: '攝像頭',
    switch_camera: '切換攝像頭',
    microphone: '麥克風',
    switch_microphone: '切換麥克風',
    microphone_volume: '麥克風音量',
    speaker: '揚聲器',
    switch_speaker: '切換揚聲器',
    volume: '音量',
    adjust_volume: '調整音量',
    test_speaker: '檢測',
    camera_error: '攝像頭被拔出或攝像頭已佔用，無法顯示視頻！ ',
    microphone_error: '麥克風被拔出或麥克風被佔用，無法使用麥克風！ ',
    mirror: '鏡像模式',
    beauty: '美顏',
    whitening: '美白',
    buffing: '磨皮',
    ruddy: '紅潤',
  },
  pretest: {
    title: '設備檢測',
    settingTitle: '設備設置',
    finishTest: '完成',
    detect_new_device: '檢測到新設備，請使用！ ',
    camera_move_out: '攝像頭被拔出，無法顯示視頻！ ',
    mic_move_out: '麥克風被拔出！ ',
    device_not_working: '設備未正常工作！ ',
    detect_new_device_in_room: '檢測到新設備，請點擊“設置”後，選擇新設備。 ',
    teacher_device_may_not_work: '老師視頻可能出現問題！ ',
  },
  'biz-header': {
    setting: '設置',
    exit: '退出',
    recording: '錄製中',
    start_record: '開啟錄製',
  },
  message: '消息',
  quiz: '提問',
  zh: '中文',
  nav: {
    delay: '延遲: ',
    network: '網絡: ',
    cpu: 'CPU: ',
    class_end: '課程結束',
    class_start: '課程開始',
    back: '返回',
    to_start_in: '距離上課還有：',
    started_elapse: '已開始上課：',
    ended_elapse: '已經下課：',
    hours: '小時',
    minutes: '分鐘',
    seconds: '秒',
    short: {
      hours: '小時',
      minutes: '分鐘',
      seconds: '秒',
    },
    signal_good: '優',
    signal_weak: '良',
    signal_bad: '差',
    signal_unknown: '未知',
  },
  tool: {
    board_name: '白板',
    screen_share: '屏幕共享',
    selector: '鼠標選擇器',
    pencil: '畫筆',
    rectangle: '矩形',
    ellipse: '橢圓',
    eraser: '橡皮擦',
    text: '文字',
    color_picker: '調色板',
    add: '新增一頁',
    upload: '上傳',
    hand_tool: '手抓工具',
    extension_tool: '擴展',
    clear: '清除',
    disk: '雲盤',
    prev: '後退',
    next: '前進',
    zoomIn: '放大',
    zoomOut: '縮小',
    fullScreen: '全屏',
    reduction: '還原',
    reset: '居中',
  },
  send: '發送',
  home: {
    form_title: '免費試用',
    roomId: 'roomId',
    roomId_placeholder: '請輸入roomId',
    userId: 'userId',
    userId_placeholder: '請輸入userId',
    roomName: '房間',
    roomName_placeholder: '請輸入房間名',
    nickName: '暱稱',
    nickName_placeholder: '請輸入暱稱',
    roomType: '類型',
    roomType_placeholder: '請選擇課堂類型',
    roomType_1v1: '1對1',
    roomType_interactiveSmallClass: '互動小班課',
    roomType_interactiveBigClass: '大班課',
    role: '角色',
    role_placeholder: '請選擇你的角色',
    role_teacher: '老師',
    role_student: '學生',
    role_assistant: '助教',
    role_audience: '觀眾',
    language: '語言：',
    language_placeholder: '請選擇語言',
    duration: '時長',
    duration_unit: '分鐘',
    enter_classroom: '進入教室',
    region_placeholder: '請選擇區域',
    region: '區域：',
    'header-left-title': '聲網靈動課堂',
    about: '關於',
    'input-error-msg': '只能輸入字母、數字',
  },
  'home-about': {
    'privacy-policy': '隱私條例',
    'product-disclaimer': '免責聲明',
    'sign-up': '註冊聲網賬號',
    'version-time': '發版時間',
    'sdk-version': 'SDK版本',
    'classroom-version': '靈動課堂版本',
    check: '查看',
    register: '註冊',
  },
  disclaimer: {
    title: '免責聲明',
    'content-a': `靈動課堂（“本產品”）是由上海兆言網絡科技有限公司（“上海兆言”）提供的一款測試產品，上海兆言享有本產品的著作權和所有權。特此免費授予獲得本產品和相關文檔文件（以下簡稱“軟件”）副本的任何人無限制地使用軟件的權利，包括但不限於使用，複製，修改，合併，發布，分發，但本產品不得用於任何商業用途，不得再許可和/或出售該軟件的副本。 `,
    'content-b': `本產品按“現狀”提供，沒有任何形式的明示擔保，包括但不限於對適配性、特定目的的適用性和非侵權性的擔保。無論是由於與本產品或本產品的使用或其他方式有關的任何合同、侵權或其他形式的行為，上海兆言均不對任何索賠、損害或其他責任負責。 `,
    'content-c': `您可以自由選擇是否使用本產品提供的服務，如果您下載、安裝、使用本產品中所提供的服務，即表明您信任該產品所有人，上海兆言對任何原因在使用本產品中提供的服務時可能對您自身或他人造成的任何形式的損失和傷害不承擔任何責任。 `,
  },
  countdown: {
    appName: '倒計時',
    seconds: '秒',
    start: '開始',
    restart: '重新開始',
  },
  hands_up_tag: '-舉手中',
  answer: {
    appName: '答題器',
    start: '開始答題',
    submit: '提交答案',
    change: '修改答案',
    'number-answered': '已答題人數',
    acc: '正確率',
    'right-key': '正確答案',
    'my-answer': '我的答案',
    over: '結束答題',
    'student-name': '學生姓名',
    'answer-time': '答題用時',
    'selected-answer': '所選答案',
    restart: '重新開始',
  },
  vote: {
    appName: '投票',
    start: '開始投票',
    restart: '重新開始',
    over: '結束投票',
    submit: '投票',
    change: '修改投票',
    'input-tip': '請輸入投票問題',
    'item-tip': '請輸入選項內容',
    'single-sel': '單選',
    'mul-sel': '多選',
  },
  no: '否',
  yes: '是',
};
