export const zh = {
  'Close Microphone': '禁用麦克风',
  'Open Microphone': '开启麦克风',
  'Camera Not Available': '摄像头已禁用',
  'Microphone Not Available': '麦克风已禁用',
  'Close Camera': '禁用摄像头',
  'Open Camera': '开启摄像头',
  'Clear Podium': '下台',
  'Clear Podiums': '全体下台',
  'Close Whiteboard': '取消授权',
  'Open Whiteboard': '授权',
  'Whiteboard Not Available': '白板已关闭',
  Star: '奖励',
  'Open Private Call': '开启私密语音',
  'Close Private Call': '关闭私密语音',
  'Camera Pos Reset': '视频复位',
  role: {
    teacher: '老师',
    student: '学生',
    assistant: '助教',
  },
  chat: {
    send_to_all: '发送全体消息',
  },
  disabled: '禁用',
  whiteboard: {
    'upload-success': '上传成功',
    'upload-error': '上传异常',
    converting: '转换中',
    'disconnect-img-alt': '白板未连接',
    'disconnect-btn': '重新连接',
    'courseWare-loading': '课件加载中，请稍候…',
    'h5-courseWare': 'H5课件',
    'test-courseWare': 'test课件',
    loading: '插入课件中……',
  },
  screen_share: '屏幕共享',
  kick: {
    kick_out_student: '移出学生',
  },
  radio: {
    kicked_once: '仅移出教室一次',
    ban: '禁止再次进入教室',
  },
  course: {
    pre_class: '课前',
    in_class: '已上课',
    end_class: '课程已结束',
    join_failed: '加入失败',
    screen_sharing: '屏幕共享',
  },
  device: {
    camera: '摄像头',
    microphone: '麦克风',
    speaker: '扬声器',
    microphone_volume: '麦克风音量',
    speaker_volume: '扬声器音量',
    stage_area: '讲台区域',
  },
  roster: {
    chat: '禁言',
    teacher_name: '教师姓名:',
    user_list: '花名册',
    student_name: '学生姓名',
    student_co_video: '上下台',
    camera_state: '摄像头',
    microphone_state: '麦克风',
    reward: '奖励',
    kick: '踢人',
    granted: '授权',
    shift: '开启',
    everyone: '全部',
    available: '非禁用',
    students_in: '学生',
    sequence: '顺序',
    random: '随机',
    order_every: '轮播',
    seconds: '秒',
    no_more_data: '没有更多数据了',
    supervise_student: '监听',
  },
  hands_up: '举手',
  on_podium_max_count: '上台人数已达上限，无法继续邀请学生上台',
  hands_up_tip: '举手请长按',
  co_video: {
    remote_open_camera: '摄像头已打开',
    remote_open_microphone: '你可以发言了',
    remote_grant_board: '你可以使用白板了',
    remote_close_camera: '摄像头已关闭',
    remote_close_microphone: '你暂时不能发言了',
    remote_revoke_board: '你现在无权使用白板了',
    received_student_hands_up: '有学生举手了',
    received_teacher_accepted: '老师已同意上台',
    received_teacher_refused: '老师拒绝了上台',
    received_student_cancel: '学生取消了举手',
    received_message_timeout: '消息未响应，请重新尝试',
    hands_up_requsted: '发送举手申请成功',
    hands_up_cancelled: '举手申请已取消',
  },
  private_media_chat: {
    chat_started: '私密聊天开始',
    chat_ended: '私密聊天结束',
  },
  placeholder: {
    muted_chat: '禁言中',
    empty_chat: '还没有消息',
    empty_quiz: '暂无提问',
    enable_chat_muted: '已开启学生禁言',
    input_message: '请输入消息',
  },
  signal: {
    delay: '网络延迟',
    lose: '丢包率',
    status: '网络状态',
    CPU: 'CPU',
    receive: '收到',
    send: '发出',
  },
  error: {
    banned: '禁止进入',
    cannot_join: '你已被禁止进入这个教室！',
    not_found: '页面找不到',
    apply_co_video_limit: '举手超出连麦人数限制',
    send_co_video_limit: '点名超出连麦人数限制',
    components: {
      paramsEmpty: '参数：{reason}不能为空',
    },
    class_end: '课程已结束，请点击确定离开教室',
    unknown: '发生未知错误，错误代码: {errCode}, 信息: {message}',
    room_is_full: '当前房间已满，请点击确认离开教室',
    network_timeout: '网络请求超时',
  },
  toast: {
    mute_chat: '你已被老师禁言了',
    unmute_chat: '你被解除禁言了',
    remote_mute_chat: '{studentName}被老师禁言了',
    remote_unmute_chat: '{studentName}被老师解除禁言了',
    add_screen_share: '老师开启了屏幕共享',
    remove_screen_share: '老师关闭了屏幕共享',
    granted_board_success: '授权白板成功',
    revoke_board_success: '收回白板成功',
    create_screen_share_failed: '创建屏幕分享失败',
    kick_by_other_side: '远端重复登录, 当前账号已离开房间',
    screen_share: {
      title: '屏幕共享',
    },
    close_ppt: '关闭当前课件',
    sure_close_ppt: '你确定要关闭吗？',
    end_class: '课程已结束',
    quit_from_room: '离开教室',
    kick_by_teacher: '你已被踢出教室',
    upload_log_failure: '上传日志失败，错误类型：{reason}, 详情参考开发者工具',
    show_log_id: `请提供你的日志ID: {no}`,
    api_login_failured: '房间加入失败, 原因: {reason}',
    confirm: '确定',
    cancel: '取消',
    leave_room: '离开教室',
    quit_room: '确定退出课程吗？',
    login_failure: '登录房间失败',
    whiteboard_lock: '设置白板跟随',
    whiteboard_unlock: '取消白板跟随',
    clear_whiteboard: '清空确认',
    clear_whiteboard_confirm: '是否清空白板内容',
    canceled_screen_share: '已取消屏幕共享',
    screen_sharing_failed: '屏幕分享失败, 原因：{reason}',
    recording_failed: '开启云录制失败, 原因：{reason}',
    start_recording: {
      title: '录制提示',
      body: '你确定要开始录制吗?',
      success: '录制开启成功',
    },
    stop_recording: {
      title: '停止录制',
      body: '你确定要停止录制吗?',
      success: '录制停止成功',
    },
    recording_too_short: '录制太短，至少15秒',
    rtm_login_failed: '房间登录失败, 请检查网络设置',
    rtm_login_failed_reason: '房间登录失败, 原因： {reason}',
    replay_failed: '回放失败，请刷新页面重试',
    teacher_exists: '该房间老师已存在，请等待30秒或重新创建教室',
    student_over_limit: '超出学生最大人数，请等待30秒或重新创建教室',
    teacher_and_student_over_limit: '超出学生和老师的最大人数',
    teacher_accept_whiteboard: '老师已授权了你白板的权限',
    teacher_cancel_whiteboard: '老师已收回了你白板的权限',
    teacher_accept_co_video: '老师已允许连麦',
    teacher_reject_co_video: '老师已拒绝连麦',
    teacher_cancel_co_video: '老师已取消连麦',
    student_cancel_co_video: '学生已取消连麦',
    student_send_co_video_apply: '"{reason}" 学生发起了连麦申请',
    student_peer_leave: '"{reason}" 离开了',
    stop_co_video: '教师停止了"{reason}"的连麦',
    reject_co_video: '您取消了学生的连麦申请',
    close_co_video: '您关闭了学生的连麦',
    close_youself_co_video: '你关闭了自己的连麦',
    accept_co_video: '您同意了连麦',
    successfully_joined_the_room: '加入房间成功',
    failed_to_join_the_room: '加入房间失败',
    failed_to_authorize_whiteboard: '授权白板失败',
    failed_to_deauthorize_whiteboard: '取消授权白板失败',
    failed_to_query_playback_list: '查询回放列表失败',
    audio_equipment_has_changed: '音频设备发生了变化',
    video_equipment_has_changed: '视频设备发生了变化',
    failed_to_initiate_screen_sharing: '发起屏幕共享失败',
    failed_to_end_screen_sharing: '结束屏幕共享失败',
    failed_to_initiate_screen_sharing_to_remote: '向远端发起屏幕共享失败',
    failed_to_enable_screen_sharing: '开启屏幕共享失败',
    failed_to_enable_screen_sharing_permission_denied: '开启屏幕共享失败！请先授权屏幕共享权限！',
    failed_to_send_chat: '发送聊天失败',
    failed_to_translate_chat: '翻译聊天失败',
    failed_to_send_reward: '发送奖励失败',
    failed_to_join_rtc_please_refresh_and_try_again: '加入rtc失败，请刷新重试',
    leave_rtc_channel: '离开rtc频道',
    failed_to_leave_rtc: '离开rtc失败',
    co_video_close_success: '下麦成功',
    co_video_close_failed: '下麦失败',
    publish_rtc_success: '发布RTC成功',
    open_whiteboard_follow: '打开白板跟随',
    close_whiteboard_follow: '关闭白板跟随',
    close_whiteboard: '关闭白板',
    close_whiteboard_confirm: '是否关闭白板',
    i: '我',
    teacher: '老师',
    the_teacher_authorized_your_whiteboard: '老师授权了你的白板',
    the_teacher_cancelled_your_whiteboard_permission: '老师取消了你的白板权限',
    publish_business_flow_successfully: '发布业务流成功',
    media_method_call_failed: '媒体方法调用失败',
    successfully_left_the_business_channel: '离开业务频道成功',
    course_started_successfully: '课程开始成功',
    setting_start_failed: '设置开始失败',
    the_course_ends_successfully: '课程结束成功',
    setting_ended_failed: '设置结束失败',
    start_recording_successfully: '开始录制成功',
    start_recording_failed: '开始录制失败',
    successfully_ended_recording: '结束录制成功',
    failed_to_end_recording: '结束录制失败',
    you_have_a_default_message: '你有一条默认消息',
    the_teacher_agreed: '老师同意了',
    student_applied: '学生申请了',
    you_were_dismissed_by_the_teacher: '你被老师下麦了',
    student_canceled: '学生取消了',
    the_teacher_refused: '老师拒绝了',
    failed_to_initiate_a_raise_of_hand_application: '发起举手申请失败',
    failed_to_end_the_call: '结束通话失败',
    failed_to_join_board: '加入白板失败',
    stop_screen_share_failed: '停止屏幕共享失败',
    classroom_remote_join: '账号在远端设备登录，您已离开教室',
    time_interval_between_start: `距离上课开始还有: {reason}分钟`,
    time_interval_between_end: `课程还有{reason}分钟结束`,
    class_is_end: `下课咯，教室还有{reason}分钟关闭`,
    time_interval_between_close: `教室还有{reason}分钟关闭`,
    reward_limit: '奖杯已全部发完',
    chat_enable: '禁言模式开启',
    chat_disable: '禁言模式关闭',
    upload_failure: '上传失败',
    download_success: '下载成功',
    download_failure: '下载失败',
    resource_already_opened: '课件已经打开',
    resource_is_converting: '课件正在转换中',
    fail_to_convert_resource: '文件转换失败',
    interaction_too_frequent: '操作过于频繁，请稍后再试',
    breakout_room_group_name_existed: '组名称已存在',
    start_group: '请先创建分组',
  },
  end_class_confirm: '确定要结束教室吗？',
  notice: {
    student_interactive_apply: `"{reason}"想和你连麦`,
  },
  scaffold: {
    clear: '清屏',
    undo: '撤销上一步操作',
    redo: '重做',
    search: '搜索',
    pencil: '画笔',
    laser_pointer: '激光笔',
    whiteboard: '白板',
    straight: '直线',
    circle: '圆圈',
    rectangle: '矩形',
    arrow: '箭头',
    pentagram: '五角星',
    rhombus: '菱形',
    triangle: '三角形',
    clicker: '鼠标',
    selector: '选择',
    eraser: '橡皮擦',
    color: '颜色',
    blank_page: '新增一页',
    move: '移动工具',
    follow: '跟随模式',
    un_follow: '解除跟随',
    screen_share: '屏幕共享',
    stop_screen_share: '停止共享',
    cloud_storage: '云盘',
    text: '文本',
    tools: '工具栏',
    user_list: '用户列表',
    breakout_room: '分组讨论',
    in_progress: '-进行中',
    not_in_progress: '-未开始',
    register: '花名册',
    save: '保存',
    slice: '截图',
    slice_window: '隐藏教室截图',
  },
  cloud: {
    fileName: '文件名',
    size: '大小',
    progress: '进度条',
    operation: '操作',
    updated_at: '修改时间',
    publicResources: '公共资源',
    deleteTip: '确认删除所选文件吗？',
    personalResources: '我的资源',
    downloadResources: '下载资源',
    upload: '上传',
    delete: '删除',
    download: '下载',
    downloading: '下载中',
    pause: '暂停',
    upload_success: '上传成功',
    supprotTypeTitle: '教室内支持的文件格式',
    fileType: '格式类型',
    ppt: 'Powerpoint演示文档',
    word: 'Word文档',
    excel: 'Excel文档',
    pdf: 'Pdf文档',
    video: '视频',
    audio: '音频',
    txt: '文本文档',
    photo: '图片',
    fileCounts: '共{fileCounts}项',
  },
  media: {
    camera: '摄像头',
    switch_camera: '切换摄像头',
    microphone: '麦克风',
    switch_microphone: '切换麦克风',
    microphone_volume: '麦克风音量',
    speaker: '扬声器',
    switch_speaker: '切换扬声器',
    volume: '音量',
    adjust_volume: '调整音量',
    test_speaker: '检测扬声器',
    camera_error: '摄像头被拔出或摄像头已占用，无法显示视频！',
    microphone_error: '麦克风被拔出或麦克风被占用，无法使用麦克风！',
    mirror: '镜像模式',
    beauty: '美颜',
    whitening: '美白',
    buffing: '磨皮',
    ruddy: '红润',
    default: '默认',
  },
  stage: {
    visible: '显示',
    hidden: '隐藏',
  },
  pretest: {
    title: '设备检测',
    settingTitle: '设备设置',
    finishTest: '完成',
    detect_new_device: '检测到新设备，请使用！',
    camera_move_out: '摄像头被拔出，无法显示视频！',
    mic_move_out: '麦克风被拔出！',
    playback_move_out: '扬声器被拔出!',
    device_move_out: '设备被拔出！',
    device_not_working: '设备未正常工作！',
    detect_new_device_in_room: '检测到新设备，请点击“设置”后，选择新设备。',
    teacher_device_may_not_work: '老师视频可能出现问题！',
  },
  'biz-header': {
    perf: 'Perf',
    setting: '设置',
    exit: '退出',
    recording: '录制中...',
    start_record: '开启录制',
    stop_record: '停止录制',
    record_starting: '录制正在准备，请稍后',
  },
  message: '消息',
  quiz: '提问',
  zh: '中文',
  nav: {
    delay: '延迟: ',
    network: '网络: ',
    cpu: 'CPU: ',
    class_end: '课程结束',
    class_start: '课程开始',
    back: '返回',
    to_start_in: '距离上课还有：',
    started_elapse: '已上课：',
    ended_elapse: '已下课：',
    class_not_started: '课程未开始',
    hours: '小时',
    minutes: '分钟',
    seconds: '秒',
    ms: '毫秒',
    short: {
      hours: '小时',
      minutes: '分钟',
      seconds: '秒',
    },
    signal_excellent: '优',
    signal_good: '良',
    signal_weak: '良',
    signal_bad: '差',
    signal_unknown: '未知',
    signal_down: '断网',
    singal_poor_tip: '当前网络质量不佳，请检查设备网络连接',
    singal_down_tip: '当前网络已断开, 请检查设备网络连接',
  },
  send: '发送',
  home: {
    form_title: '免费试用',
    roomId: 'roomId',
    roomId_placeholder: '请输入roomId',
    userId: 'userId',
    userId_placeholder: '请输入userId',
    roomName: '房间',
    roomName_placeholder: '请输入房间名',
    nickName: '昵称',
    nickName_placeholder: '请输入昵称',
    roomType: '类型',
    roomType_placeholder: '请选择课堂类型',
    serviceType: '服务',
    serviceType_placeholder: '请选择音视频服务',
    serviceType_premium: '实时互动（RTC）',
    serviceType_standard: '轻互动（极速直播）',
    serviceType_latency: '弱互动（CDN）',
    serviceType_mix: '混合服务（CDN&RTC）',
    serviceType_mix_stream_cdn: '合流转推',
    serviceType_hosting_scene: '伪直播',
    roomType_1v1: '1对1',
    roomType_interactiveSmallClass: '互动小班课',
    roomType_interactiveBigClass: '大班课',
    roomType_vocationalClass: '职教大班课',
    role: '角色',
    role_placeholder: '请选择你的角色',
    encryptionMode: '模式',
    encryptionMode_placeholder: '请选择加密模式',
    encryptionKey: '密匙',
    encryptionKey_placeholder: '请输入密钥',
    role_teacher: '老师',
    role_student: '学生',
    role_assistant: '助教',
    role_audience: '观众',
    role_observer: '监课',
    language: '语言：',
    language_placeholder: '请选择语言',
    duration: '时长',
    duration_unit: '分钟',
    enter_classroom: '进入教室',
    region_placeholder: '请选择区域',
    region: '区域：',
    'header-left-title': '声网灵动课堂',
    about: '关于',
    'input-error-msg': '只能输入6-50位字符(字母、数字)',
    'input-username-error-msg': '只能输入3-25位字符(文字、字母、数字、空格)',
    network_error: '当前网络异常，请稍后再试',
    'recordation-search': '课程回放',
    'recordation-tip': '只能查询1小时内的回放',
    replay: '回放',
    search: '查询',
    system_name: '声网灵动课堂',
  },
  'home-about': {
    'privacy-policy': '隐私条例',
    'product-disclaimer': '免责声明',
    'sign-up': '注册声网账号',
    'build-time': '构建时间',
    'sdk-version': 'SDK版本',
    'classroom-version': '灵动课堂版本',
    'commit-id': 'Commit ID',
    check: '查看',
    register: '注册',
  },
  disclaimer: {
    title: '免责声明',
    'content-a': `灵动课堂（“本产品”）是由上海兆言网络科技有限公司（“上海兆言”）提供的一款测试产品，上海兆言享有本产品的著作权和所有权。特此免费授予获得本产品和相关文档文件（以下简称“软件”）副本的任何人无限制地使用软件的权利，包括但不限于使用，复制，修改，合并，发布，分发，但本产品不得用于任何商业用途，不得再许可和/或出售该软件的副本。 `,
    'content-b': `本产品按“现状”提供，没有任何形式的明示担保，包括但不限于对适配性、特定目的的适用性和非侵权性的担保。无论是由于与本产品或本产品的使用或其他方式有关的任何合同、侵权或其他形式的行为，上海兆言均不对任何索赔、损害或其他责任负责。 `,
    'content-c': `您可以自由选择是否使用本产品提供的服务，如果您下载、安装、使用本产品中所提供的服务，即表明您信任该产品所有人，上海兆言对任何原因在使用本产品中提供的服务时可能对您自身或他人造成的任何形式的损失和伤害不承担任何责任。`,
  },
  confirm: {
    delete: '删除提示',
  },
  stream: {
    'placeholder.loading': '正在打开摄像头',
    'placeholder.muted': '摄像头关闭',
    'placeholder.broken': '摄像头损坏',
    'placeholder.notpresent.teacher': '老师不在教室',
    'placeholder.notpresent.student': '学生不在教室',
  },
  screenshare: {
    display: '屏幕{reason}',
  },
  toast2: {
    'teacher.turn.off.my.mic': '老师已关闭你的麦克风，你暂时不能发言了',
    'teacher.turn.on.my.mic': '老师已打开你的麦克风，你可以开始发言了',
    'teacher.turn.off.my.cam': '老师已关闭你的摄像头',
    'teacher.turn.on.my.cam': '老师已打开你的摄像头',
    'teacher.grant.permission': '你已被老师授权，请使用白板工具互动',
    'teacher.revoke.permission': '你已被老师收回授权，无法使用白板工具互动',
    'teacher.accept.onpodium': '老师邀请你上台了，与大家积极互动吧',
    'teacher.revoke.onpodium': '你离开讲台了，暂时无法与大家互动',
    'teacher.reward': '祝贺{reason}获得奖励',
    'teacher.reward2': '祝贺{reason1}等{reason2}位同学获得奖励',
    screen_permission_denied: '使用屏幕共享前，请先打开屏幕录制权限',
    stream_window_full: '视频窗口数量已达{reason}人上限',
    save_success: '保存成功',
    save_error: '保存失败',
    saving: '正在导出，请稍候…',
    screen_shot_permission_denied: '使用屏幕截图前，请授权打开应用的访问权限',
  },
  breakout_room: {
    create_prefix: '创建',
    create_suffix: '个讨论组',
    auto: '自动分配',
    manual: '手动分配',
    wait_for_assign1: '待分配{reason}人',
    wait_for_assign2: '，每组{reason}人',
    wait_for_assign3: '每组{reason}人',
    create_submit: '创建',
    cancel_submit: '取消',
    assign: '分配',
    re_create: '重新创建',
    add_group: '添加讨论组',
    start: '开始讨论',
    stop: '结束讨论',
    move_to: '移动至',
    change_to: '交换组',
    group_label: '讨论组',
    rename: '修改名称',
    remove: '删除讨论组',
    not_grouped: '未分组',
    confirm_invite_teacher_content: '{reason1}小组中的{reason2}请求帮助',
    confirm_invite_student_btn_ok: '确定',
    confirm_invite_student_btn_cancel: '取消',
    confirm_ask_for_help_absent_content: '老师不在教室中',
    confirm_ask_for_help_btn_cancel: '取消',
    already_in_room: '已经在这个小组了',
    not_accepted: '(未接受)',
    joined: '已加入',
    student: '学生',
    broadcast_message: '发送全体消息',
    send: '发送',
    cancel: '取消',
    broadcast_message_success: '消息发送成功',
    broadcast_message_cannot_be_empty: '消息不能为空',
    group_is_full: '该小组已满{reason}人',
    confirm_stop_group_title: '确定结束分组讨论？',
    confirm_stop_group_content: '结束后，所有学员将返回大房间',
    confirm_stop_group_sure: '结束',
    confirm_delete_group_title: '删除小组',
    confirm_delete_group_content: '确定要删除 {reason} 吗？',
    confirm_join_group_title: '加入小组',
    confirm_join_group_content: '加入 “{reason}” ？',
    send_to_all_placeholder: '这是一条全体消息，最多300字',
    create_group: '创建讨论组',
    group_number: '讨论组个数',
    group_type: '分配方式',
    group_tips: '将教室内容复制到讨论组',
    user_panel_empty: '暂无可分配学生',
    group_current_has_students: '{reason}人',
    group_current_empty: '暂无学生',
  },
  /** Breakout Room  */
  fcr_group_help_title: '请求帮助',
  fcr_group_help_content: '你可以邀请老师进入小组帮助你',
  fcr_group_help_teacher_busy_msg: '老师正在忙，请稍后重试',
  fcr_group_teacher_is_helping_others_msg: '	老师正在帮助其他讨论组，请稍后重试',
  fcr_group_teacher_exist_hint: '老师已在小组内',
  fcr_group_invite: '邀请',
  fcr_group_invitation: '老师邀请您加入{reason}',
  fcr_group_button_join: '加入',
  fcr_group_button_later: '稍后',
  fcr_group_joining: '正在加入{reason}',
  fcr_group_join: '加入讨论组',
  fcr_group_enter_welcome: '欢迎加入{reason}与大家互动讨论',
  fcr_group_enter_group: '{reason1}{reason2}进入小组',
  fcr_group_exit_group: '{reason1}{reason2}离开小组',
  fcr_group_close_group: '老师结束了小组讨论',
  fcr_group_invite_back_main_room: '老师邀请你回到大房间',
  fcr_group_back_main_room: '正在回到大房间...',
  fcr_group_back_sure: '确定',
  fcr_group_back_cancel: '取消',
  fcr_group_back_exit: '退出',
  fcr_group_back_to_main_room: '回到大房间',
  fcr_group_exit_room: '离开教室',
  fcr_group_student_not_in_room: '用户未进入分组',
  fcr_group_sure: '确定',
  /** Breakout Room  */
  /** Remote Control */
  fcr_share_title_teacher: '教师屏幕共享',
  fcr_share_title_singel_window: '支持单个窗口共享',
  fcr_share_title_full_screen: '支持全屏共享',
  fcr_share_title_sound: '不支持声音',
  fcr_share_title_all_student: '学生屏幕共享',
  fcr_share_title_any_student: '可指定任意学生屏幕',
  fcr_share_selected: '已选择{reason}',
  fcr_share_sharing: '正在分享{reason}屏幕',
  fcr_share_authorized_control: '老师已授权你控制屏幕',
  fcr_share_forbidden_control: '老师已回收你的屏幕控制权',
  fcr_share_device_not_support: '{reason} 上课设备不支持远程控制',
  fcr_share_Remote_control_disconnected: '{reason} 离开房间，已断开远程控制权',
  fcr_share_reminded_student_agree:
    '{reason1} 尚未同意共享屏幕，提醒{reason2} 单击“同意”按钮共享自己的屏幕',
  fcr_share_teacher_requesting_share: '老师正在请求分享并操作你的屏幕，请选择同意或暂不处理',
  fcr_share_stopped_student_share: '老师已停止共享你的屏幕',
  fcr_share_no_student: '当前教室没有学生，无法开启学生屏幕共享',
  fcr_share_device_no_support: '学生设备不支持远程控制，无法开启学生屏幕共享',
  fcr_rc_control_bar_allow_student_control: '允许{reason}控制',
  fcr_rc_control_bar_disallow_student_control: '不允许学生控制',
  fcr_share_title_select_window_share: '请选择一个要共享的窗口',
  fcr_share_title_desktop: '桌面',
  fcr_share_title_application: '应用',
  fcr_share_title_share_window: '开始共享',
  fcr_share_button_agree: '同意',
  fcr_share_title_controling: '正在控制',
  fcr_share_switch: '切换共享内容',
  fcr_rc_control_anti_virus_software_conflict:
    '如无法正常使用远程控制功能，请关闭杀毒软件和电脑管家。',
  fcr_close: '关闭',
  fcr_online_courseware_label_file_type: '外部分享课件',
  fcr_online_courseware: '在线课件',
  fcr_online_courseware_button_upload_online_file: '上传在线课件',
  fcr_online_courseware_button_upload: '上传',
  fcr_online_courseware_button_close: '关闭',
  fcr_online_courseware_label_link: '课件链接',
  fcr_online_courseware_label_file_name: '课件名',
  fcr_online_courseware_label_uploadpage: '上传在线课件',
  fcr_please_input: '请输入',
  fcr_online_courseware_input_content: '请输入课件链接以及课件名',
  fcr_online_courseware_valid_url: '请输入正确的课件链接',
  fcr_alert_title: '提示',
  fcr_alert_submit: '确认',
  fcr_alert_cancel: '取消',
  settings_setting: '设置',
  fcr_settings_option_general: '常规设置',
  fcr_settings_option_about_us: '关于我们',
  settings_logout: '退出登录',
  settings_logout_alert: '是否确认退出登录？',
  settings_nickname: '昵称设置',
  fcr_settings_label_region: '区域设置',
  settings_theme: '主题设置',
  settings_theme_light: '明亮',
  settings_theme_dark: '暗黑',
  fcr_settings_label_language: '语言设置',
  settings_close_account: '账号注销',
  fcr_settings_option_general_language_simplified: '简体中文',
  fcr_settings_option_general_language_traditional: '繁体中文',
  fcr_settings_option_general_language_english: '英文',
  fcr_settings_label_about_us_about_us: '关于我们',
  fcr_settings_link_about_us_privacy_policy: '隐私条例',
  fcr_settings_link_about_us_user_agreement: '用户协议',
  fcr_settings_label_about_us_fcr_ver: '灵动课堂版本',
  fcr_settings_label_about_us_sdk_ver: 'SDK版本',
  settings_disclaimer: '免责声明',
  settings_register: '注册声网账号',
  settings_publish_time: '发版时间',
  settings_logoff_detail: {
    1: '很遗憾，灵动课堂无法继续为您提供服务，感谢您一直以来的陪伴。确认账号注销后会产生以下效果：',
    2: '1.删除账号关联的课堂数据；',
    3: '2.删除账号及手机号信息；',
    4: '若需要再次使用请重新注册。',
  },

  settings_logoff_agreenment: '我已阅读并确认注销账号',
  settings_logoff_submit: '确认注销',
  settings_logoff_alert: '是否确认注销账号？',
  fcr_vocational_teacher_absent: '老师当前不在教室中',
  fcr_vocational_video_start_early_alert: '提前上课将立即播放课程录像，是否确认？',

  /** Remote Control */
  begin_class: '开始上课',
  edu_error: {
    '600000': '房间资源未获取',
    '600001': '加入房间失败',
    '600002': '无文件扩展名,上传失败',
    '600003': '文件格式不支持,上传失败',
    '600004': '文件上传阿里云失败',
    '600005': '文件上传失败',
    '600006': '白板未获取',
    '600007': '白板资源未获取',
    '600008': '白板加入失败',
    '600009': '白板关闭失败',
    '600010': '白板API添加失败',
    '600011': '白板窗口管理不可用',
    '600012': '不支持的文件格式，不可使用',
    '600013': '教室未准备好',
    '600014': '踢出房间失败',
    '600015': '本地用户信息未获取',
    '600016': '下台失败',
    '600017': '驳回举手失败',
    '600018': '取消举手失败',
    '600019': '轮播启动失败',
    '600020': '轮播停止失败',
    '600021': '禁言失败',
    '600022': '组件关闭失败',
    '600023': '同意上台失败',
    '600024': '举手失败',
    '600025': '插件关闭失败',
    '600026': '数据错误',
    '600027': '奖励发放失败',
    '600028': '启用视频失败',
    '600029': '禁用视频失败',
    '600030': '切换视频失败',
    '600031': '启用音频失败',
    '600032': '禁用音频失败',
    '600033': '切换音频失败',
    '600034': '白板加载失败',
    '600035': '开始录制失败',
    '600036': '结束录制失败',
    '600037': '加入RTC频道失败',
    '600038': '离开RTC频道失败',
    '600039': '加入白板失败',
    '600040': '离开白板失败',
    '600041': '无效的教室状态',
    '600042': '无效的RTC状态',
    '600043': '无效的白板状态',
    '600044': '离开教室失败',
    '600045': 'RTE未初始化',
    '600046': '举手失败',
    '600047': '白板不可操作',
    '600048': '获取聊天记录失败',
    '600049': '获取私聊记录失败',
    '600050': '获取私聊列表',
    '600051': '聊天发送失败',
    '600052': '聊天发送失败',
    '600053': '禁言失败',
    '600054': '解除禁言失败',
    '600055': '设备管理器未初始化',
    '600056': '学生数量错误',
    '600057': '删除云盘资源失败',
    '600058': '加载云盘资源失败',
    '600059': '课堂状态更新失败',
    '600060': '开启屏幕共享失败',
    '600061': '停止屏幕共享失败',
    '600062': '本地设备状态更新失败',
    '600063': '远端设备状态更新失败',
    '600064': '文件上传失败',
    '600065': 'ExtApp状态更新失败',
    '600066': 'ExtApp状态更新失败',
    '600067': '课件转换失败',
    '600068': '课件正在转换中',
    '600069': '全员下台失败',
    '600070': '白板状态更新失败',
    '600071': '教室未初始化',
    '600072': '白板连接超时',
    '600073': '信息上报失败',
    '600074': '课件已打开',
    '600075': '上台失败',
    '600077': '获取上传记录失败',
    '600078': '切换大小流失败',
    '600079': '开启大小流失败',
    '600080': '设置小流参数失败',
    '600090': '加入RDC房间失败',
  },
  edu_serv_error: {
    '20400200': '未传入用户唯一标识',
    '20400300': '未传入流信息',
    '20401000': '用户 Token 无效',
    '20401001': '此角色不能加入房间',
    '20403001': '教室内该角色人数已达上限，无法进入',
    '20403002': '房间人数已达上限，无法进入',
    '20404000': '进程不存在',
    '20404100': '房间不存在',
    '20410101': '房间已过期',
    '20404200': '用户不存在',
    '20404300': '流信息不存在',
    '20404400': '房间模板不存在',
    '20409000': '进程冲突',
    '20409100': '房间冲突',
    '20409300': '流ID冲突',
    '20410100': '房间已结束',
    '20410200': '用户不在线',
    '20500300': '流创建失败',
    '20500001': '生成 Token 失败',
    '30403100': '你不能加入教室',
    '30400420': '请去控制台设置白板Token',
    '30403200': '你不能发送聊天信息',
    '30404200': '老师不在教室',
    '30409100': '课程已开始',
    '30409101': '课程已结束',
    '30409102': '屏幕已共享',
    '30409103': '屏幕未共享',
    '30409104': '房间类型冲突',
    '30409410': '录制未开始',
    '30409411': '录制运行中',
    '30400412': '参数 "url" 或 "rootUrl" 在网页录制模式必填',
    '30500420': '白板创建失败',
    '30409440': '房间奖励已达上限',
    '30409430': '操作冲突',
    '30404430': '私人聊天未找到',
    '30404460': '举手功能未配置',
    '30404461': '学生未举手',
    '30409460': '学生已拒收',
    '30404462': '该学生未上台',
    '30410460': '配置举手功能未开启',
    '30429460': '举手人数到达最大上限',
    '30429461': '上台到达最大上限',
    '30409601': '用户正在被邀请',
  },
  marketing: {
    title: '赠券',
    search: '搜索',
    table: {
      name: '姓名',
      role: '角色',
      loading: '正在加载更多...',
      end: '到底了',
      role_teacher: '老师',
      role_student: '学生',
      role_assistant: '助教',
      role_audience: '观众',
    },
    footer: {
      discount: '优惠金额',
      unit: '元',
      send: '发送',
      errorMsg: '只能输入数字',
    },
    receive: {
      ok: '去使用',
      cancel: '残忍拒绝',
      title: '恭喜',
      context: '点击"去使用"跳转到商品链接',
      coupon: '优惠券',
      unit: '元',
    },
    send: {
      success: '发送优惠券成功',
      fail: '发送优惠券失败',
    },
  },
  invite: {
    title: '邀请上台',
    clear_podium: '关闭上台',
    accept_podium: '允许上台',
    inviting_podium: '邀请中',
    invite_podium: '邀请上台',
    confirm: {
      title: '提示',
      content: '老师邀请你上台交流，点击确定上台 点击取消忽略',
      ok: '确认',
      cancel: '取消',
    },
  },
  vocational: {
    handsUp: '申请上台',
    handsUpReviewing: '审核中',
    offPodium: '停止上台',
  },
  question: '提问',
  fcr_copy_title: '分享',

  fcr_copy_room_name: '房间:',
  fcr_copy_share_link: '邀请链接:',
  fcr_copy_share_link_copy: '复制链接',
  fcr_copy_success: '复制成功',
};
