export enum PageRouter {
  LoginPage = 'login',
  Home = 'home',
  Welcome = 'welcome',
  CreateRoom = 'create_room',
  JoinRoom = 'join_room',
  Invite = 'invite_room',
  Launch = 'launch',

  H5Welcome = 'welcome_h5',
  H5JoinRoom = 'join_room_h5',
  H5Invite = 'invite_room_h5',
  FlexHome = 'flex_home',
  FlexH5Home = 'flex_h5_home',
  VocationalHome = 'vocational_home',
  VocationalHomeH5Home = 'vocational_h5_home',
  Setting = 'setting',
  OneToOne = '1v1',
  MidClass = 'small',
  BigClass = 'big',
  PretestPage = 'pretest',
  ShareLinkPage = 'share_home',
  AuthTokenPage = 'auth_token',
  TestRecordPage = 'test_record',
  TestH5HomePage = 'test_h5_home',
  RecordationSearchPage = 'recordation-search',
  Window = 'window',
}
