export enum BizPageRouter {
  Setting = 'setting',
  OneToOne = '1v1',
  MidClass = 'small',
  BigClass = 'big',
  OneToOneIncognito = '1v1_incognito',
  SmallClassIncognito = 'small_incognito',
  LaunchPage = 'launch',
  PretestPage = 'pretest',
  TestHomePage = 'test_home',
  ShareLinkPage = 'share_home',
  Incognito = 'Incognito',
  TestRecordPage = 'test_record',
  TestH5HomePage = 'test_h5_home',
  TestAdapteHomePage = 'test_adapte_home',
  RecordationSearchPage = 'recordation-search',
  Window = 'window',
  VocationalHomePage = 'vocational_home',
  VocationalHomeH5Page = 'vocational_h5_home',
}
